(function(root,factory){const api=factory(root.V113_DOMAIN,root.V113_STORE,root.V113_ROUTER,root.V113_COMPONENTS);root.V113_ARCHITECT=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(DOMAIN,STORE,ROUTER,C){
'use strict';
const STAGES={dashboard:'Orientación',clients:'Contexto de marca',library:'Exploración',calendar:'Planificación',factory:'Creación',production:'Producción',shim:'Extracción / automatización',airesults:'Hidratación IA',assets:'Assets',branding:'Brand Intelligence',guide:'Guía',roadmap:'Roadmap',studio:'Revisión 1×1'};
const EXPLAIN={dashboard:'Aquí decides qué hacer ahora. El Dashboard prioriza siguiente acción y trabajo por rol.',factory:'He crea piezas o lotes desde una idea, brief o campaña y compila prompts separados de contenido/visual.',shim:'Shim convierte una transcripción con timestamps en candidatos, carruseles y un handoff confirmable para automatización.',production:'Production muestra qué falta terminar. Elige un rol para ver solo la parte relevante.',studio:'Content Studio abre una sola pieza y la proyecta por guion, copy, grabación, diseño, edición, QA y publicación.',library:'Biblioteca muestra todos los Contents; úsala para buscar, filtrar y abrir una pieza existente.',calendar:'Calendar organiza fecha y backlog sin duplicar Contents.',assets:'Assets vincula archivos al content_id y slot correctos.',airesults:'Resultados IA devuelve resultados externos a la pieza original con preview/mapping.',clients:'Clientes contiene Brand Core, formatos, Quality Packs y Source Truth.',branding:'Brand Intelligence organiza criterio y las 25 tools del Branding Method.',guide:'Guía explica los flujos completos.',roadmap:'Roadmap muestra qué está construido, qué se valida y qué sigue.'};
function architectContextV113(){const s=STORE.getState(),content=s.selectedContentId?DOMAIN.contentById(s.selectedContentId):null;const pending=content?DOMAIN.openTasks(content):[];return{section:s.section,stage:STAGES[s.section]||'ABRAXAS',presentationMode:s.presentationMode,roleMode:s.roleMode,contentId:content?.id||null,contentTitle:content?.title||null,lifecycle:content?.lifecycle||null,progress:content?DOMAIN.productionProgress(content):null,pending,filters:s.filters,nextAction:content?DOMAIN.nextAction(content):null,explanation:EXPLAIN[s.section]||'Estás dentro de ABRAXAS.'};}
function route(target,label,why,firstAction,expectedResult,successCondition,extra={}){return{target,label,why,firstAction,expectedResult,successCondition,...extra};}
function architectResolveV113(query=''){const q=String(query||'').trim().toLowerCase(),ctx=architectContextV113();let title='Siguiente paso',summary=ctx.explanation,routes=[];
  if(/crear contenido|crear una pieza|crear algo|donde.*crear|contenido nuevo/.test(q)){title='¿Dónde puedo crear contenido?';summary='Depende de cuál sea tu punto de partida.';routes=[route('factory','He · Content Factory','Partes de una idea, brief, campaña o tema.','Elige cliente → formato físico → patrón → objetivo/contexto.','Prompt editorial + visual o pieza AI READY.','El prompt queda exportable o la pieza queda guardada en Biblioteca.'),route('shim','Shim','Partes de una grabación, podcast o transcripción.','Pega transcript con timestamps y define outputs/estructuras.','HTML de revisión + master JSON + manifests.','Los candidatos quedan revisables y solo CONFIRMADOS pasan a automatización.'),route('library','Biblioteca / Studio','Ya existe una pieza y quieres extenderla o corregirla.','Busca el Content y abre la vista adecuada.','La misma pieza actualizada, sin duplicar content_id.','El cambio queda guardado y la siguiente tarea se actualiza.')];}
  else if(/grabar|grabaci|talento|teleprompter|guion/.test(q)){title='Preparar grabación';routes=[route('production','Recording Desk','Necesitas ver qué se graba y qué falta.','Cambia el rol a Grabación y abre la primera pieza.','Guion, delivery, plano y checklist.','El master/source queda vinculado o la tarea de grabación se marca resuelta.',{role:'recording'}),route('studio','Guion / Talento','Necesitas que el speaker lea solo lo que le interesa.','Abre la pieza en Guion / Talento y activa Teleprompter.','Solo texto hablado + delivery opcional.','La persona puede grabar sin navegar capas de edición.',{view:'script'})];}
  else if(/copy|copies|caption/.test(q)){title='Resolver copies';routes=[route('production','Copy Desk','Agrupa todos los copies pendientes.','Cambia a rol Copy y abre una pieza.','Copy actual + prompt + Cómo usarlo.','El copy queda aprobado en la misma pieza.',{role:'copy'}),route('studio','Studio · Copies','Trabajas un contenido concreto.','Abre Copies dentro del Content Studio.','Copies por plataforma y prompt especializado.','Los slots de copy quedan completos.',{view:'copy'})];}
  else if(/editar|edicion|editor|b-roll|vfx|sfx|music|música|davinci/.test(q)){title='Preparar edición';routes=[route('production','Editing Desk','Quieres ver todas las piezas que necesitan montaje.','Cambia al rol Edición.','Lista priorizada de timelines pendientes.','Cada pieza tiene source/B-roll/VFX/SFX/Music y dependencias visibles.',{role:'editing'}),route('studio','Studio · Edición','Necesitas trabajar un timeline concreto.','Abre la pieza en Edición.','Beat-by-beat con capas audiovisuales y prompts.','La edición puede ejecutarse sin reconstruir contexto.',{view:'editing'}),route('shim','Shim / DaVinci','Vienes de un podcast/transcripción y necesitas crear timelines automáticamente.','Revisa candidatos y exporta el manifest confirmado.','davinciPackage + script importable.','Resolve recibe la misma selección editorial confirmada.')];}
  else if(/diseño|design|imagen|slide|portada|cover/.test(q)){title='Resolver diseño';routes=[route('production','Design Desk','Quieres ver slides, covers y stills pendientes.','Cambia al rol Diseño.','Lista por asset/slot.','Cada asset queda vinculado al Content correcto.',{role:'design'}),route('studio','Studio · Diseño','Trabajas una pieza concreta.','Abre Diseño y revisa texto aprobado + visual + prompts.','Prompt CON/SIN texto y asset slot.','El asset queda aprobado y visible en Studio.',{view:'design'})];}
  else if(/publicar|calendar|fecha|hoy|semana/.test(q)){title='Planificar/publicar';routes=[route('calendar','Calendario','Quieres ordenar fechas/backlog.','Abre Calendar y mueve la pieza.','scheduledAt actualizado sin duplicar el Content.','La pieza aparece en la fecha correcta.'),route('production','Publishing Desk','Quieres saber qué bloquea publicación.','Cambia al rol Publicación.','Assets, QA, copy y fecha visibles.','Lifecycle puede avanzar a READY/PUBLISHED.',{role:'publishing'})];}
  else if(/que hago|qué hago|primero|siguiente|ahora/.test(q)||!q){title='Siguiente paso';const n=ctx.nextAction;if(n)routes=[route(n.target,n.label,`Es la primera dependencia abierta de ${ctx.contentTitle}.`,n.description,'Tarea resuelta / estado actualizado.',n.successCondition)];else routes=[route(ctx.section,STAGES[ctx.section]||'Continuar',ctx.explanation,'Sigue la acción principal de la pantalla.','Un output claro o una siguiente acción.','La pantalla deja de mostrar un bloqueo.')];}
  else{title='Entiendo la pantalla y te propongo una ruta';routes=[route(ctx.section,STAGES[ctx.section]||'Continuar',ctx.explanation,ctx.nextAction?.description||'Revisa la acción principal de esta pantalla.','Un resultado ejecutable.',ctx.nextAction?.successCondition||'La siguiente etapa queda disponible.')];}
  return{title,summary,routes,context:ctx};}
function setArchitectQueryV113(q){STORE.set({architectQuery:q});if(typeof rootRender==='function')rootRender();}
function architectGoV113(target,role,view){if(role)STORE.set({roleMode:role});if(view&&STORE.getState().selectedContentId)return ROUTER.openContent(STORE.getState().selectedContentId,view,'architect');return ROUTER.go(target);}
function prepareArchitectExternalPromptV113(){const s=STORE.getState(),ctx=architectContextV113(),answer=architectResolveV113(s.architectQuery||'¿Qué hago primero?');return `ABRAXAS · CONTEXTUAL HELP HANDOFF · v1.1.3\n\nCONTEXTO\nSección: ${ctx.section}\nEtapa: ${ctx.stage}\nRol: ${ctx.roleMode}\nModo: ${ctx.presentationMode}\nContent ID: ${ctx.contentId||'ninguno'}\nLifecycle: ${ctx.lifecycle||'no aplica'}\nProgreso: ${ctx.progress??'no aplica'}\nPendientes: ${ctx.pending.map(t=>t.label).join(', ')||'ninguno'}\n\nPREGUNTA\n${s.architectQuery||answer.title}\n\nRESPONDE CON\n1. Dónde entrar/clicar.\n2. Por qué.\n3. Qué dato pegar/elegir.\n4. Qué resultado esperar.\n5. Qué hacer después.\n6. Condición exacta de terminado.\nNo inventes funciones que no estén descritas por este contexto.`;}
function renderArchitectV113(){if(!STORE.getState().architectOpen)return'';const s=STORE.getState(),ctx=architectContextV113(),answer=architectResolveV113(s.architectQuery);return `<aside class="architect-panel-v113 glass-layer"><header><div class="v113-architect-mark">${C.icon('architect')}</div><div><b>El Arquitecto</b><small>Guía contextual · v1.1.3</small></div><button class="v113-icon-btn" onclick="V113_SHELL.toggleArchitectV113()">${C.icon('close')}</button></header><section class="v113-architect-context"><span>Etapa</span><b>${C.esc(ctx.stage)}</b><p>${C.esc(ctx.explanation)}</p>${ctx.contentId?`<div class="v113-architect-content"><strong>${C.esc(ctx.contentTitle)}</strong><small>${C.esc(ctx.contentId)} · ${ctx.progress}% · ${C.esc(ctx.lifecycle)}</small></div>`:''}</section><div class="v113-architect-quick">${['¿Qué hago primero?','¿Dónde puedo crear contenido?','¿Qué tengo pendiente?','¿Dónde hago copies?','¿Dónde edito?','¿Cómo publico?'].map(q=>`<button onclick="setArchitectQueryV113(${JSON.stringify(q)})">${q}</button>`).join('')}</div><section class="v113-architect-answer"><span>Siguiente paso</span><h3>${C.esc(answer.title)}</h3><p>${C.esc(answer.summary)}</p><div class="v113-route-list">${answer.routes.map(r=>`<article><div><b>${C.esc(r.label)}</b><p>${C.esc(r.why)}</p><small><strong>Primero:</strong> ${C.esc(r.firstAction)}</small><small><strong>Resultado:</strong> ${C.esc(r.expectedResult)}</small><small><strong>Termina cuando:</strong> ${C.esc(r.successCondition)}</small></div><button class="v113-btn primary" onclick="architectGoV113('${r.target}','${r.role||''}','${r.view||''}')">Ir →</button></article>`).join('')}</div></section><div class="v113-architect-input"><input value="${C.esc(s.architectQuery)}" onkeydown="if(event.key==='Enter')setArchitectQueryV113(this.value)" placeholder="Ej. ¿Dónde puedo crear contenido?"><button onclick="setArchitectQueryV113(this.previousElementSibling.value)">↵</button></div><footer><button class="v113-btn" onclick="copyTextV113(prepareArchitectExternalPromptV113())">Preparar pregunta para IA</button><small>Local-first. No envía datos automáticamente.</small></footer></aside>`;}
return{architectContextV113,architectResolveV113,renderArchitectV113,setArchitectQueryV113,architectGoV113,prepareArchitectExternalPromptV113};
});
