(function(root,factory){const api=factory(root.V113_STORE||(typeof require!=='undefined'?require('./store.js'):null));root.V113_BRAIN=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(STORE){
'use strict';
const BRAIN_ANATOMY=['left_hemisphere','right_hemisphere','interhemispheric_fissure','frontal_lobe','parietal_lobe','temporal_lobe','occipital_lobe','cerebellar_hint','gyri_sulci'];
const MORPH_TARGETS=['brain','routes','content_graph','production_flow','calendar','published_network'];
const PARTICLE_GLYPH='open-chevron';
let runtime=null;
function clampZoom(v){return Math.max(1,Math.min(2,Number(v)||1));}
function randFactory(seed=113){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296);}
function ellipse(x,y,cx,cy,rx,ry){const dx=(x-cx)/rx,dy=(y-cy)/ry;return dx*dx+dy*dy<=1;}
function anatomicalMask(x,y){
  // normalized x,y in [-1,1]; union of lobes with a visible central fissure.
  const left=ellipse(x,y,-.22,-.02,.63,.78)||ellipse(x,y,-.42,-.30,.46,.48)||ellipse(x,y,-.48,.24,.42,.43)||ellipse(x,y,-.13,.43,.36,.34);
  const right=ellipse(x,y,.22,-.02,.63,.78)||ellipse(x,y,.42,-.30,.46,.48)||ellipse(x,y,.48,.24,.42,.43)||ellipse(x,y,.13,.43,.36,.34);
  const lower=ellipse(x,y,0,.56,.35,.22);
  const fissure=Math.abs(x)<(.032 + .02*(1-Math.min(1,Math.abs(y)))) && y<.52;
  const temporalCut=(Math.abs(x)>.68 && y>.37);
  return (left||right||lower)&&!fissure&&!temporalCut&&y<.78;
}
function generateBrainPoints(count,w,h,zoom=1){const r=randFactory(113113),pts=[],z=clampZoom(zoom),cx=w*.58,cy=h*.47,s=Math.min(w,h)*.48*z;let guard=0;while(pts.length<count&&guard<count*100){guard++;const x=r()*2-1,y=r()*1.72-.88;if(anatomicalMask(x,y)){const wobble=(r()-.5)*1.6;pts.push({x:cx+x*s*.90+wobble,y:cy+y*s*.72+wobble,phase:r()*Math.PI*2,size:1.1+r()*2.0,alpha:.36+r()*.58});}}while(pts.length<count)pts.push({x:cx,y:cy,phase:0,size:1.5,alpha:.5});return pts;}
function targetPoints(name,count,w,h,zoom=1){if(name==='brain')return generateBrainPoints(count,w,h,zoom);const pts=[],r=randFactory(551+name.length),cx=w*.58,cy=h*.48,ww=w*.55,hh=h*.60;for(let i=0;i<count;i++){let x,y;if(name==='routes'){const lane=i%6,rows=Math.ceil(count/6);x=w*.28+(lane/5)*ww;y=h*.18+((Math.floor(i/6)%rows)/(rows||1))*hh+(r()-.5)*8;}else if(name==='content_graph'){const a=(i/count)*Math.PI*2*5,rr=(.08+.38*(i/count))*Math.min(w,h);x=cx+Math.cos(a)*rr;y=cy+Math.sin(a)*rr*.62;}else if(name==='production_flow'){const col=i%5,row=Math.floor(i/5)%8;x=w*.22+col*(ww/4)+(r()-.5)*14;y=h*.18+row*(hh/7)+(r()-.5)*10;}else if(name==='calendar'){const col=i%7,row=Math.floor(i/7)%6;x=w*.23+col*(ww/6)+(r()-.5)*6;y=h*.20+row*(hh/5)+(r()-.5)*6;}else{const a=r()*Math.PI*2,rr=Math.sqrt(r())*Math.min(w,h)*.38;x=cx+Math.cos(a)*rr;y=cy+Math.sin(a)*rr*.68;}pts.push({x,y,phase:r()*Math.PI*2,size:1+r()*1.8,alpha:.35+r()*.6});}return pts;}
function drawGyri(ctx,w,h,zoom){const z=clampZoom(zoom),cx=w*.58,cy=h*.47,s=Math.min(w,h)*.48*z;ctx.save();ctx.strokeStyle='rgba(238,215,170,.11)';ctx.lineWidth=1;ctx.globalAlpha=.9;const curves=[[-.58,-.38,-.34,-.56,-.05,-.48],[-.64,-.12,-.40,-.24,-.08,-.14],[-.61,.17,-.38,.08,-.08,.22],[-.47,.42,-.24,.30,-.05,.48],[.58,-.38,.34,-.56,.05,-.48],[.64,-.12,.40,-.24,.08,-.14],[.61,.17,.38,.08,.08,.22],[.47,.42,.24,.30,.05,.48],[-.30,-.62,-.46,-.40,-.28,-.20],[.30,-.62,.46,-.40,.28,-.20],[-.30,.02,-.44,.24,-.23,.39],[.30,.02,.44,.24,.23,.39]];for(const c of curves){ctx.beginPath();ctx.moveTo(cx+c[0]*s*.9,cy+c[1]*s*.72);ctx.bezierCurveTo(cx+c[2]*s*.9,cy+c[3]*s*.72,cx+c[4]*s*.9,cy+c[5]*s*.72,cx+(c[4]*.68)*s*.9,cy+(c[5]+.13)*s*.72);ctx.stroke();}ctx.strokeStyle='rgba(255,255,255,.16)';ctx.beginPath();ctx.moveTo(cx,cy-s*.61);ctx.bezierCurveTo(cx-s*.015,cy-s*.20,cx+s*.012,cy+s*.20,cx,cy+s*.38);ctx.stroke();ctx.restore();}
function drawParticle(ctx,p,t){const pulse=.78+.22*Math.sin((t||0)*.001+p.phase),size=Math.max(1.2,p.size*1.15);ctx.globalAlpha=p.alpha*pulse;ctx.strokeStyle=p.alpha>.72?'#f6ead2':p.alpha>.52?'#d8b46c':'#a27c42';ctx.lineWidth=Math.max(.65,size*.38);ctx.beginPath();ctx.moveTo(p.x-size,p.y+size*.52);ctx.lineTo(p.x,p.y-size*.72);ctx.lineTo(p.x+size,p.y+size*.52);ctx.stroke();}
function drawBrainStructure(ctx,w,h,zoom){const z=clampZoom(zoom),cx=w*.58,cy=h*.47,s=Math.min(w,h)*.48*z;ctx.save();ctx.globalAlpha=1;ctx.strokeStyle='rgba(246,234,210,.18)';ctx.lineWidth=1.15;ctx.beginPath();if(typeof ctx.ellipse==='function'){ctx.ellipse(cx-s*.20,cy-s*.02,s*.48,s*.55,-.08,0,Math.PI*2);ctx.ellipse(cx+s*.20,cy-s*.02,s*.48,s*.55,.08,0,Math.PI*2);ctx.ellipse(cx-s*.17,cy+s*.48,s*.25,s*.15,-.08,0,Math.PI*2);ctx.ellipse(cx+s*.17,cy+s*.48,s*.25,s*.15,.08,0,Math.PI*2);}ctx.stroke();ctx.strokeStyle='rgba(216,180,108,.18)';ctx.beginPath();ctx.moveTo(cx,cy-s*.58);ctx.bezierCurveTo(cx-s*.012,cy-s*.28,cx+s*.014,cy+s*.12,cx,cy+s*.37);ctx.stroke();ctx.strokeStyle='rgba(216,180,108,.09)';ctx.beginPath();const anchors=[[-.38,-.26],[-.16,-.42],[.16,-.42],[.38,-.26],[-.43,.06],[-.18,.18],[.18,.18],[.43,.06],[-.28,.40],[0,.50],[.28,.40]];for(let i=0;i<anchors.length-1;i++){const a=anchors[i],b=anchors[i+1];ctx.moveTo(cx+a[0]*s,cy+a[1]*s);ctx.lineTo(cx+b[0]*s,cy+b[1]*s);}ctx.stroke();drawGyri(ctx,w,h,z);ctx.restore();}
function morph(name){if(!runtime||!MORPH_TARGETS.includes(name))return;runtime.target=name;runtime.targets=targetPoints(name,runtime.particles.length,runtime.w,runtime.h,runtime.zoom);}
function setZoom(value){const z=clampZoom(value);STORE?.set({brainZoom:z});if(runtime){runtime.zoom=z;runtime.targets=targetPoints(runtime.target,runtime.particles.length,runtime.w,runtime.h,z);}return z;}
function init(canvasId='v113BrainCanvas'){
  if(typeof document==='undefined')return null;const canvas=document.getElementById(canvasId);if(!canvas)return null;if(runtime?.raf)cancelAnimationFrame(runtime.raf);const ctx=canvas.getContext('2d');if(!ctx)return null;const rect=canvas.getBoundingClientRect?.()||{width:innerWidth||1200,height:700},w=Math.max(800,rect.width||1200),h=Math.max(520,rect.height||700),dpr=Math.min(2,devicePixelRatio||1);canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const reduced=matchMedia?.('(prefers-reduced-motion: reduce)')?.matches||false,count=w<900?680:1120,zoom=clampZoom(STORE?.getState?.().brainZoom||1),r=randFactory(933),particles=Array.from({length:count},()=>({x:w*(.35+r()*.45),y:h*(.22+r()*.52),phase:r()*6.28,size:1+r()*1.8,alpha:.35+r()*.6}));runtime={canvas,ctx,w,h,particles,targets:targetPoints('brain',count,w,h,zoom),target:'brain',zoom,reduced,raf:null};function tick(t=0){ctx.clearRect(0,0,w,h);if(runtime.target==='brain')drawBrainStructure(ctx,w,h,runtime.zoom);for(let i=0;i<particles.length;i++){const p=particles[i],q=runtime.targets[i],ease=reduced?1:.055;p.x+=(q.x-p.x)*ease;p.y+=(q.y-p.y)*ease;if(!reduced&&runtime.target==='brain'){p.x+=Math.sin(t*.00045+p.phase)*.025;p.y+=Math.cos(t*.00038+p.phase)*.018;}drawParticle(ctx,p,t);}ctx.globalAlpha=1;if(!reduced)runtime.raf=requestAnimationFrame(tick);}tick(performance?.now?.()||0);return runtime;}
function destroy(){if(runtime?.raf&&typeof cancelAnimationFrame!=='undefined')cancelAnimationFrame(runtime.raf);runtime=null;}
function observeStory(){if(typeof document==='undefined'||typeof IntersectionObserver==='undefined')return;const obs=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){const t=e.target.getAttribute('data-brain-target');if(t)morph(t);}}, {threshold:.46});document.querySelectorAll('[data-brain-target]').forEach(el=>obs.observe(el));return obs;}
return{BRAIN_ANATOMY,MORPH_TARGETS,PARTICLE_GLYPH,clampZoom,generateBrainPoints,targetPoints,anatomicalMask,drawBrainStructure,init,destroy,morph,setZoom,observeStory,get runtime(){return runtime;}};
});
