(function(root,factory){const api=factory(root.V113_DOMAIN,root.V113_STORE,root.V113_ROUTER,root.V113_COMPONENTS,root.ABRAXAS_CORE);root.V113_FACTORY=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(DOMAIN,STORE,ROUTER,C,CORE){
'use strict';
const PHYSICAL=CORE.PHYSICAL||{reel:{label:'Reel / vertical'},carousel:{label:'Carrusel'},horizontal:{label:'Video horizontal'},linkedin:{label:'Post LinkedIn'},newsletter:{label:'Newsletter'},article:{label:'Nota / artículo'},stories:{label:'Stories'},image:{label:'Imagen / post'}};
function draft(){const s=STORE.getState();if(s.factoryDraft)return s.factoryDraft;const d={mode:'piece',clientId:'abraxas',physicalType:'reel',patternId:'',universalId:'',pillar:'',topic:'',objective:'',audience:'',quantity:1,window:'2_weeks',cadence:{lot1:'medium',lot2:'medium',lot3:'medium'},useExisting:false};STORE.set({factoryDraft:d});return d;}
function setFactoryFieldV113(key,val){const d={...draft()};if(key.startsWith('cadence.')){const k=key.split('.')[1];d.cadence={...d.cadence,[k]:val};}else d[key]=val;STORE.set({factoryDraft:d});if(typeof rootRender==='function')rootRender();}
function client(){return DOMAIN.clientById(draft().clientId)||DOMAIN.allClients()[0];}
function pattern(){const c=client();return c?.patterns?.find(p=>p.id===draft().patternId)||c?.patterns?.[0]||null;}
function universal(){return DOMAIN.data.universalPatterns?.find(p=>p.id===draft().universalId)||null;}
function synthetic(){const d=draft(),c=client(),p=pattern(),structure=CORE.mergeStructures(d.physicalType,p,universal()),units=structure.map((x,i)=>({id:`u${i+1}`,label:x.name,name:x.name,function:x.function,text:`[GENERAR] ${d.topic||d.objective||x.name}`,recording:'Definir según función y formato.',visualDirection:'Definir visual específico según Quality Pack y función narrativa.',broll:'',vfx:{},sfx:{},music:{}}));return{id:`draft-${d.clientId}-${d.physicalType}`,clientId:d.clientId,title:d.topic||'Nueva pieza ABRAXAS',physicalType:d.physicalType,formatName:p?.name||CORE.physicalTypeLabel(d.physicalType),recipeClient:p?.name||'',recipeUniversal:universal()?.name||'',pillar:d.pillar||c?.pillars?.[0]||'',intention:d.objective||'Crear contenido con criterio',audience:d.audience||'audiencia prioritaria',problem:d.topic||'problema por definir',desiredChange:d.objective||'cambio por definir',summary:d.topic||'',thesis:d.topic||'',primaryPlatform:'Instagram',platforms:['Instagram','LinkedIn'],lifecycle:'BUILD',scheduledAt:null,lot:'L1',structure,units,copies:{},promptInputs:{structure}};}
function compiled(){const c=client(),x=synthetic();return{content:x,editorial:CORE.compileEditorialPrompt(x,c,{...draft(),structure:x.structure}),visual:CORE.compileVisualPrompt(x,c,{...draft(),structure:x.structure})};}
function saveFactoryDraftV113(){const pack=compiled(),d=draft(),id=CORE.uid?CORE.uid(`${d.clientId}-${d.physicalType}`):`content-${Date.now()}`;const c={...pack.content,id,lifecycle:'AI_READY',history:[{version:1,at:new Date().toISOString(),reason:'He v1.1.3',summary:'Pieza creada desde Content Factory.'}],expectedAssets:[],productionTasks:[{id:`${id}-copy`,type:'copy',label:'Copies',description:'Completar copies por plataforma.',status:'ready_prompt'},{id:`${id}-visual`,type:'visual',label:'Visuales',description:'Resolver visual y assets.',status:'ready_prompt'},{id:`${id}-qa`,type:'qa',label:'QA',description:'Revisar formato, claims y visual.',status:'ready_prompt'},{id:`${id}-publish`,type:'publish',label:'Publicación',description:'Calendarizar/publicar.',status:'ready_prompt'}]};DOMAIN.data.contents.unshift(c);ROUTER.openContent(id,'overview','factory');return c;}
function renderPiece(){const d=draft(),c=client(),p=pattern(),pack=compiled();return `<div class="v113-factory-layout"><section class="v113-panel v113-factory-form"><div class="v113-field"><label>Cliente</label><select onchange="setFactoryFieldV113('clientId',this.value)">${DOMAIN.allClients().map(x=>`<option value="${x.id}" ${x.id===d.clientId?'selected':''}>${C.esc(x.name)}</option>`).join('')}</select></div><div class="v113-format-grid">${Object.entries(PHYSICAL).map(([id,v])=>`<button class="${id===d.physicalType?'active':''}" onclick="setFactoryFieldV113('physicalType','${id}')"><b>${C.esc(v.label)}</b><small>Formato físico</small></button>`).join('')}</div><div class="v113-field"><label>Formato / patrón del cliente</label><select onchange="setFactoryFieldV113('patternId',this.value)">${(c?.patterns||[]).map(x=>`<option value="${x.id}" ${x.id===p?.id?'selected':''}>${C.esc(x.name)}</option>`).join('')}</select></div><div class="v113-form-grid"><label>Tema<input value="${C.esc(d.topic)}" oninput="setFactoryFieldV113('topic',this.value)"></label><label>Objetivo<input value="${C.esc(d.objective)}" oninput="setFactoryFieldV113('objective',this.value)"></label><label>Audiencia<input value="${C.esc(d.audience)}" oninput="setFactoryFieldV113('audience',this.value)"></label><label>Cantidad<select onchange="setFactoryFieldV113('quantity',Number(this.value))">${[1,2,3,4,5,6].map(n=>`<option ${n===d.quantity?'selected':''}>${n}</option>`).join('')}</select></label></div></section><section class="v113-panel v113-factory-result"><span>PROMPT COMPOSER</span><h3>${C.esc(pack.content.title)}</h3><p>${C.esc(pack.content.structure.map(x=>x.name).join(' → '))}</p>${C.disclosure('Prompt editorial',`<pre class="v113-prompt">${C.esc(pack.editorial)}</pre>`,true)}${C.disclosure('Prompt visual',`<pre class="v113-prompt">${C.esc(pack.visual)}</pre>`,false)}<div class="v113-card-actions">${C.button('Guardar como AI READY',{kind:'primary',onclick:'saveFactoryDraftV113()'})}</div></section></div>`;}
function renderBatch(){const d=draft(),plan=CORE.buildBatchPlan({window:d.window,cadence:d.cadence,useExisting:d.useExisting,existing:DOMAIN.allContents()});return `<div class="v113-batch"><section class="v113-panel"><div class="v113-form-grid"><label>Ventana<select onchange="setFactoryFieldV113('window',this.value)"><option value="1_week" ${d.window==='1_week'?'selected':''}>1 semana</option><option value="2_weeks" ${d.window==='2_weeks'?'selected':''}>2 semanas</option><option value="1_month" ${d.window==='1_month'?'selected':''}>1 mes</option></select></label>${['lot1','lot2','lot3'].map(k=>`<label>${k.toUpperCase()}<select onchange="setFactoryFieldV113('cadence.${k}',this.value)">${['low','medium','high'].map(v=>`<option ${d.cadence[k]===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('')}</div><label class="v113-check"><input type="checkbox" ${d.useExisting?'checked':''} onchange="setFactoryFieldV113('useExisting',this.checked)"> Usar contenido existente cuando encaje</label></section><section class="v113-batch-plan">${plan.map(x=>`<article class="v113-panel"><span>Semana ${x.week} · ${x.lot}</span><h3>${C.esc(x.role)}</h3><p>${C.esc(CORE.physicalTypeLabel(x.physicalType))}</p>${C.pill(x.status)}</article>`).join('')}</section></div>`;}
function render(){const d=draft();return `<section class="v113-factory">${C.sectionTitle('He · Content Factory','Crea una pieza o un lote. El formato físico manda; los patrones añaden ADN y estructura.')}<div class="v113-segmented v113-factory-mode"><button class="${d.mode==='piece'?'active':''}" onclick="setFactoryFieldV113('mode','piece')">Crear pieza</button><button class="${d.mode==='batch'?'active':''}" onclick="setFactoryFieldV113('mode','batch')">Crear lote</button></div>${d.mode==='piece'?renderPiece():renderBatch()}</section>`;}
return{render,setFactoryFieldV113,saveFactoryDraftV113,compiled,draft};
});
