(function(root,factory){const api=factory(root.V113_STORE||(typeof require!=='undefined'?require('./store.js'):null),root.V113_ROUTER||(typeof require!=='undefined'?require('./router.js'):null),root.V113_COMPONENTS||(typeof require!=='undefined'?require('./components.js'):null));root.V113_SHELL=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(STORE,ROUTER,C){
'use strict';
const NAV=[['dashboard','Home','dashboard'],['clients','Clientes','clients'],['library','Biblioteca','library'],['calendar','Calendario','calendar'],['factory','He · Content Factory','factory'],['production','Producción','production'],['shim','Shim','shim'],['airesults','Resultados IA','airesults'],['assets','Assets','assets'],['branding','Brand Intelligence','branding'],['guide','Guía','guide'],['roadmap','Roadmap','roadmap']];
const ROLE_OPTIONS=[['all','Yo hago todo'],['strategy','Estrategia'],['script','Guion / Talento'],['copy','Copy'],['recording','Grabación'],['design','Diseño'],['editing','Edición'],['qa','QA'],['publishing','Publicación']];
function sectionName(id){return NAV.find(x=>x[0]===id)?.[1]||'ABRAXAS';}
function setPresentationModeV113(mode){STORE.set({presentationMode:mode});if(typeof rootRender==='function')rootRender();}
function setRoleModeV113(role){STORE.set({roleMode:role});if(typeof rootRender==='function')rootRender();}
function toggleSidebarV113(){const s=STORE.getState();STORE.set({sidebarCollapsed:!s.sidebarCollapsed});if(typeof rootRender==='function')rootRender();}
function toggleCommandV113(){const s=STORE.getState();STORE.set({commandOpen:!s.commandOpen});if(typeof rootRender==='function')rootRender();}
function toggleArchitectV113(){const s=STORE.getState();STORE.set({architectOpen:!s.architectOpen});if(typeof rootRender==='function')rootRender();}
function renderSidebar(){const s=STORE.getState();return `<aside class="v113-sidebar glass-layer ${s.sidebarCollapsed?'collapsed':''} ${s.presentationMode==='story'?'sidebar-story-hidden':''}"><div class="v113-sidebar-brand">${C.brandIcon()}<div><b>ABRAXAS</b><small>Creative Operations System</small></div><button class="v113-icon-btn" onclick="toggleSidebarV113()" aria-label="${s.sidebarCollapsed?'Expandir':'Contraer'} sidebar">${C.icon('menu')}</button></div><nav>${NAV.map(([id,label,ic])=>`<button class="v113-nav-item ${s.section===id?'active':''}" onclick="V113_ROUTER.go('${id}')">${C.icon(ic)}<span>${label}</span><i>${C.icon('chevron')}</i></button>`).join('')}</nav><div class="v113-sidebar-foot"><span>v1.1.3</span><small>Interface System 3.0</small></div></aside>`;}
function renderTopbar(){const s=STORE.getState();return `<header class="v113-topbar glass-layer"><div class="v113-top-left"><button class="v113-icon-btn workspace-menu-v113" onclick="toggleSidebarV113()" aria-label="Abrir navegación">${C.icon('menu')}</button><div><b>${sectionName(s.section)}</b><small>${s.roleMode==='all'?'Vista completa':ROLE_OPTIONS.find(x=>x[0]===s.roleMode)?.[1]||s.roleMode}</small></div></div><div class="v113-top-actions"><div class="v113-segmented presentation-toggle-v113"><button class="${s.presentationMode==='dashboard'?'active':''}" onclick="setPresentationModeV113('dashboard')">Dashboard</button><button class="${s.presentationMode==='story'?'active':''}" onclick="setPresentationModeV113('story')">Product Story</button></div><label class="v113-role-select"><span>Rol</span><select name="roleMode" onchange="setRoleModeV113(this.value)">${ROLE_OPTIONS.map(([id,label])=>`<option value="${id}" ${id===s.roleMode?'selected':''}>${label}</option>`).join('')}</select></label><button class="v113-icon-btn command-launcher-v113" onclick="toggleCommandV113()" aria-label="Abrir Command Palette">⌘K</button></div></header>`;}
function renderCommand(){const s=STORE.getState();if(!s.commandOpen)return'';return `<div class="v113-command-backdrop" onclick="if(event.target===this)toggleCommandV113()"><section class="v113-command glass-layer"><div class="v113-command-input">${C.icon('search')}<input id="v113CommandInput" placeholder="Buscar herramienta, contenido o acción…" oninput="filterV113Command(this.value)"><button onclick="toggleCommandV113()">Esc</button></div><div id="v113CommandResults">${NAV.map(([id,label,ic])=>`<button data-command-label="${label.toLowerCase()}" onclick="V113_ROUTER.go('${id}')">${C.icon(ic)}<span>${label}</span><small>Abrir workspace</small></button>`).join('')}</div></section></div>`;}
function renderArchitectLauncher(){return `<button class="architect-launcher-v113 glass-layer" onclick="toggleArchitectV113()" aria-label="Abrir El Arquitecto">${C.icon('architect')}<span>El Arquitecto</span></button>`;}
function renderShellFrame(content){const s=STORE.getState();return `<div class="v113-app ${s.presentationMode==='story'?'is-story':'is-dashboard'} ${s.sidebarCollapsed?'sidebar-collapsed':''}">${renderSidebar()}<div class="v113-main">${renderTopbar()}<main class="v113-workspace">${content}</main></div>${renderCommand()}${renderArchitectLauncher()}<div id="v113ArchitectMount"></div><div id="v113ToastMount"></div></div>`;}
return {NAV,ROLE_OPTIONS,renderShellFrame,renderSidebar,renderTopbar,renderCommand,renderArchitectLauncher,setPresentationModeV113,setRoleModeV113,toggleSidebarV113,toggleCommandV113,toggleArchitectV113};
});
