(function(root,factory){const api=factory(root.V113_DOMAIN,root.V113_STORE,root.V113_COMPONENTS,root.ABRAXAS_CORE);root.V113_SHIM=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(DOMAIN,STORE,C,CORE){
'use strict';
const STRUCTURES=[['friction','Fricción → criterio → regla','Hook literal que abre tensión → mecanismo → payoff.'],['contrast','Afirmación → contraste → decisión','Afirmación fuerte → matiz → argumento → decisión.'],['story','Historia → descubrimiento → implicación','Open loop real → contexto → giro → implicación.'],['horizontal','Tesis → capítulos → payoff','8–12 min, capítulos coherentes y trazables.'],['intro','Podcast intro cinematográfico','Footage → VO+B-roll → footage, ~80 s.'],['carousel','Carrusel editorial complementario','Idea → mecanismo/framework → implicación, sin transcribir slides.']];
function shim(){const s=STORE.getState();if(s.shimDraft)return s.shimDraft;const d={step:1,clientId:'abraxas',sourceLabel:'',context:'',transcript:'',verticalEnabled:true,verticalMax:true,verticalCount:8,horizontalEnabled:true,horizontalCount:2,carouselEnabled:true,carouselAuto:true,carouselCount:6,platforms:['Instagram','LinkedIn','YouTube'],structureMode:'smart',structures:['friction','contrast','story','horizontal','intro','carousel'],customStructure:''};STORE.set({shimDraft:d});return d;}
function setShimFieldV113(k,v){const d={...shim(),[k]:v};STORE.set({shimDraft:d});if(typeof rootRender==='function')rootRender();}
function toggleShimArrayV113(k,v){const d={...shim()},a=new Set(d[k]||[]);a.has(v)?a.delete(v):a.add(v);d[k]=[...a];STORE.set({shimDraft:d});if(typeof rootRender==='function')rootRender();}
function client(){return DOMAIN.clientById(shim().clientId)||DOMAIN.allClients()[0];}
function qualityContext(c){const q=c?.qualityPack||{};return [`CLIENTE: ${c?.name||''}`,`QUÉ ES: ${(q.whatIs||[]).join(' | ')}`,`QUÉ NO ES: ${(q.whatIsNot||[]).join(' | ')}`,`VOZ: ${(q.voice||[]).join(' | ')}`,`VISUAL: ${typeof q.visual==='string'?q.visual:JSON.stringify(q.visual||{})}`,`QUALITY GATES: ${(q.qualityGates||[]).join(' | ')}`,`SOURCE TRUTH: ${(q.sourceTruth||[]).join(' | ')}`].join('\n');}
function shimPackage(){const d=shim(),c=client(),cfg={...d,clientName:c?.name,context:[d.context,'CLIENT QUALITY CONTEXT',qualityContext(c)].filter(Boolean).join('\n\n')},prompt=CORE.buildShimPrompt(cfg);return{prompt,request:{version:'1.1.3',type:'ABRAXAS_SHIM_REQUEST',clientId:d.clientId,qualityVersion:c?.qualityVersion||'1.1.3',config:cfg,resultContract:['editable_html','master_json','SHIM_CONFIRMED_MANIFEST','CUT_AUTOMATION_PACKAGE','CAROUSEL_PRODUCTION_PACKAGE','terminalPackage','davinciPackage']}};}
function applyJocPodcastPresetV113(){const d={...shim(),clientId:'joc',context:'JOC Podcast · preservar speakers, timestamps y texto exacto. Calidad primero y evitar sesgo sistemático entre JOC e invitado. La voz en off del intro añade contexto/stakes y nunca se atribuye al speaker.',verticalEnabled:true,verticalMax:true,verticalCount:12,horizontalEnabled:true,horizontalCount:2,carouselEnabled:true,carouselAuto:true,carouselCount:6,platforms:['Instagram','TikTok','LinkedIn','YouTube','YouTube Shorts'],structureMode:'smart',structures:['friction','contrast','story','horizontal','intro','carousel']};STORE.set({shimDraft:d});if(typeof rootRender==='function')rootRender();}
function nav(){const s=shim();return `<div class="v113-wizard-nav"><button class="v113-btn" ${s.step<=1?'disabled':''} onclick="setShimFieldV113('step',${Math.max(1,s.step-1)})">← Anterior</button><span>Paso ${s.step}/5</span><button class="v113-btn primary" ${s.step>=5?'disabled':''} onclick="setShimFieldV113('step',${Math.min(5,s.step+1)})">Siguiente →</button></div>`;}
function step1(){const s=shim(),c=client();return `<div class="v113-wizard-stage"><span>01 · Fuente</span><h2>Empieza por la grabación original.</h2><p>No limpies el transcript: los timestamps y el texto fuente sostienen la automatización.</p><div class="v113-shim-client-row"><label>Cliente / Quality Pack<select onchange="setShimFieldV113('clientId',this.value)">${DOMAIN.allClients().map(x=>`<option value="${x.id}" ${x.id===s.clientId?'selected':''}>${C.esc(x.name)}</option>`).join('')}</select></label><button class="v113-btn" onclick="applyJocPodcastPresetV113()">Preset JOC Podcast</button></div><div class="v113-howto"><b>${C.esc(c?.name||'Cliente')}</b><p>Shim incorporará el Quality Pack, formato, visual, límites y Source Truth del cliente al Master Prompt.</p></div><label>Nombre<input value="${C.esc(s.sourceLabel)}" oninput="setShimFieldV113('sourceLabel',this.value)"></label><label>Contexto<textarea oninput="setShimFieldV113('context',this.value)">${C.esc(s.context)}</textarea></label><label>Transcripción con timestamps<textarea class="v113-shim-transcript" oninput="setShimFieldV113('transcript',this.value)">${C.esc(s.transcript)}</textarea></label>${nav()}</div>`;}
function step2(){const s=shim();return `<div class="v113-wizard-stage"><span>02 · Qué quieres obtener</span><h2>Define los outputs.</h2><div class="v113-shim-output"><article><b>Verticales</b><label><input type="checkbox" ${s.verticalEnabled?'checked':''} onchange="setShimFieldV113('verticalEnabled',this.checked)"> Activar</label><small>50–90 s · ideal 50–80</small></article><article><b>Horizontales</b><label><input type="checkbox" ${s.horizontalEnabled?'checked':''} onchange="setShimFieldV113('horizontalEnabled',this.checked)"> Activar</label><small>8–12 min</small></article><article><b>Carruseles</b><label><input type="checkbox" ${s.carouselEnabled?'checked':''} onchange="setShimFieldV113('carouselEnabled',this.checked)"> Activar</label><small>Complementarios, no transcripción</small></article></div><div class="v113-quality-strip"><span>CUT_AUTOMATION_PACKAGE</span><span>CAROUSEL_PRODUCTION_PACKAGE</span><span>Terminal / FFmpeg</span><span>DaVinci Resolve</span></div>${nav()}</div>`;}
function step3(){const s=shim();return `<div class="v113-wizard-stage"><span>03 · Estructuras</span><h2>Elige cómo debe pensar la selección.</h2><div class="v113-structure-grid">${STRUCTURES.map(([id,t,d])=>`<button class="${s.structures.includes(id)?'active':''}" onclick="toggleShimArrayV113('structures','${id}')"><b>${t}</b><small>${d}</small></button>`).join('')}</div><label>Estructura personalizada<textarea oninput="setShimFieldV113('customStructure',this.value)">${C.esc(s.customStructure)}</textarea></label>${nav()}</div>`;}
function step4(){const pack=shimPackage(),s=shim();return `<div class="v113-wizard-stage"><span>04 · Revisar</span><h2>Qué le pedirás realmente a la IA.</h2><div class="v113-review-grid"><article class="v113-panel"><b>${s.sourceLabel||'Sin nombre'}</b><small>Fuente</small></article><article class="v113-panel"><b>${s.structures.length}</b><small>Estructuras</small></article><article class="v113-panel"><b>${pack.request.resultContract.length}</b><small>Outputs contractuales</small></article></div><pre class="v113-prompt">${C.esc(pack.prompt.slice(0,7000))}</pre>${nav()}</div>`;}
function step5(){const pack=shimPackage();return `<div class="v113-wizard-stage"><span>05 · Exportar</span><h2>El paquete de análisis ya está listo.</h2><p>El HTML resultante será la mesa de revisión. Solo CONFIRMADO entra al manifest de automatización.</p><div class="v113-export-grid"><button onclick="copyTextV113(V113_SHIM.shimPackage().prompt)"><b>Copiar Master Prompt</b><small>Ejecutar en IA externa</small></button><button onclick="downloadV113('ABRAXAS_SHIM_REQUEST_v1.1.3.json',JSON.stringify(V113_SHIM.shimPackage().request,null,2))"><b>JSON de solicitud</b><small>Contrato reproducible</small></button><button><b>SHIM_CONFIRMED_MANIFEST</b><small>Se crea después de la revisión humana</small></button><button><b>Terminal + DaVinci</b><small>Mismo manifest, dos ejecutores</small></button></div>${C.disclosure('Prompt completo',`<pre class="v113-prompt">${C.esc(pack.prompt)}</pre>`,false)}${nav()}</div>`;}
function render(){const s=shim(),steps=[step1,step2,step3,step4,step5];return `<section class="v113-shim">${C.sectionTitle('Shim','Transcript → review HTML → decisiones confirmadas → Terminal/DaVinci.')}<div class="v113-quality-strip v113-shim-contracts"><span>SHIM_CONFIRMED_MANIFEST</span><span>CUT_AUTOMATION_PACKAGE</span><span>CAROUSEL_PRODUCTION_PACKAGE</span></div><div class="v113-stepper">${['Fuente','Qué quieres obtener','Estructuras','Revisar','Exportar'].map((x,i)=>`<button class="${s.step===i+1?'active':''} ${s.step>i+1?'done':''}" onclick="setShimFieldV113('step',${i+1})"><span>${i+1}</span>${x}</button>`).join('')}</div><section class="v113-panel v113-shim-stage">${steps[s.step-1]()}</section></section>`;}
return{render,shim,setShimFieldV113,toggleShimArrayV113,shimPackage,applyJocPodcastPresetV113,STRUCTURES};
});
