const assert=require('assert');
const app=require('../src/app.js');
const core=require('../src/core.js');
const data=require('../src/data.js');
assert.equal(app.VERSION,'1.1.2');
assert.equal(app.monthCells('2026-08').length,42);
const cal=app.renderCalendar();
assert(cal.includes('Calendario editorial'));
assert(cal.includes('calendarBacklog'));
assert(cal.includes('Leyenda'));
assert(cal.includes('draggable="true"'));
app.state.factory.mode='batch';
app.state.factory.clientId='moka';
app.state.factory.batch.window='2_weeks';
app.state.factory.batch.cadence={lot1:'high',lot2:'medium',lot3:'low'};
const batch=app.renderFactoryBatch();
assert(batch.includes('Cadencia Lote 1'));
assert(batch.includes('Cadencia Lote 2'));
assert(batch.includes('Cadencia Lote 3'));
assert(batch.includes('data-lot-cadence="lot1"'));
assert(batch.includes('data-lot-cadence="lot2"'));
assert(batch.includes('data-lot-cadence="lot3"'));
assert(batch.includes('Baja')&&batch.includes('Media')&&batch.includes('Alta'));
const counts=core.lotCadenceCounts(app.state.factory.batch.cadence);
assert.deepEqual(counts,{lot1:4,lot2:2,lot3:1});
const plan=core.buildBatchPlan({window:'2_weeks',cadence:app.state.factory.batch.cadence,useExisting:false,existing:[]});
assert.equal(plan.filter(x=>x.lot==='L1').length,8);
assert.equal(plan.filter(x=>x.lot==='L2').length,4);
assert.equal(plan.filter(x=>x.lot==='L3').length,2);
app.state.factory.mode='piece';
app.state.factory.quantity=6;
const he=app.renderFactory();
assert(he.includes('Crear pieza')&&he.includes('Crear lote'));
for(let i=1;i<=6;i++)assert(he.includes(`>${i}<`));
const promptContent=data.contents[0];
const p=core.compileEditorialPrompt(promptContent,data.clients[0],promptContent.promptInputs);
assert(core.scorePrompt(p).pass);

const video=data.contents.find(c=>['reel','horizontal'].includes(c.physicalType));
const carousel=data.contents.find(c=>c.physicalType==='carousel');
const videoHtml=app.renderStudioContent(video);
assert(videoHtml.includes('Omni / VFX · source video'));
assert(videoHtml.includes('Referencias visuales · START / MIDDLE / END'));
assert(videoHtml.includes('B-roll · video independiente'));
assert(videoHtml.includes('SFX · generación / búsqueda'));
const carHtml=app.renderStudioContent(carousel);
assert(carHtml.includes('Imagen del slide · CON texto'));
assert(carHtml.includes('Imagen del slide · SIN texto'));
const unitPrompt=core.compileUnitOmniPrompt(video,video.units[0],0,data.clients.find(x=>x.id===video.clientId));
assert(core.scorePrompt(unitPrompt).pass);



app.state.ui.section='shim';
app.state.shim=app.defaultShim();
const shimHtml=app.renderShim();
assert(shimHtml.includes('shim-stepper')&&shimHtml.includes('Fuente')&&shimHtml.includes('Exportar'));
assert.equal(app.state.shim.step,1);
const ctx=app.architectContext();
assert.equal(ctx.section,'shim');
assert(ctx.locationTitle.includes('Shim'));
const a1=app.architectAnswer('first');
assert(a1.body.length>30);
const createGuide=app.architectSearch('¿Dónde puedo crear contenido?');
assert(createGuide.suggestions.some(x=>x.target==='factory'));
assert(createGuide.suggestions.some(x=>x.target==='shim'));
assert(createGuide.suggestions.every(x=>x.reason&&x.successCondition));
assert('campaignId' in ctx && 'lifecycle' in ctx && 'selection' in ctx && 'pending' in ctx);
const ap=app.prepareArchitectQuestion();
assert(ap.includes('ABRAXAS')&&ap.includes('Shim'));
const launcher=app.renderArchitectLauncher();
assert(launcher.includes('architect-app-icon'));

console.log('runtime node tests PASS');

// Product Story remains available, but Dashboard is the default operating representation
assert.equal(app.VERSION,'1.1.2');
app.state.ui.presentationMode='dashboard';
assert.equal(app.isProductStorySection('dashboard'),false);
app.state.ui.presentationMode='story';
assert.equal(app.isProductStorySection('dashboard'),true);
assert.equal(app.isProductStorySection('clients'),true);
assert.equal(app.isProductStorySection('branding'),true);
assert.equal(app.isProductStorySection('roadmap'),true);
assert.equal(app.isProductStorySection('factory'),false);
app.state.ui.section='dashboard';app.state.ui.storyMode='visual';
const dashStory=app.renderDashboard();
assert(dashStory.includes('Get the highlights'));
assert(dashStory.includes('Take a closer look.'));
assert(dashStory.includes('homeBrainField'));
assert(dashStory.includes('data-brain-target'));
assert(dashStory.includes('Take a closer look.'));
assert(dashStory.includes('story-highlight-rail'));
assert(!dashStory.includes('metric-strip'));
assert(dashStory.includes('data-story-section="closer"'));
app.state.ui.storyMode='text';
const dashText=app.renderDashboard();
assert(dashText.includes('story-text-document'));
assert(!dashText.includes('story-highlight-rail'));
app.state.ui.storyMode='visual';
const localNav=app.renderStoryLocalNav('dashboard');
assert(localNav.includes('Visual'));
assert(localNav.includes('Solo texto'));
assert(localNav.includes('Secciones'));
assert(localNav.includes('Qué quieres hacer'));
app.state.ui.section='clients';
const clientsStory=app.renderClients();
assert(clientsStory.includes('Una infraestructura.')&&clientsStory.includes('Cuatro criterios distintos.'));
assert(clientsStory.includes('story-slide-controls'));
assert(clientsStory.includes('story-disclosure'));
assert(clientsStory.includes('story-highlight-rail'));
app.state.ui.section='branding';
app.state.ui.brandingView='landing';
let brandStory=app.renderBranding();
assert(brandStory.includes('Conocer el Branding Method'));
assert(brandStory.includes('Ver aplicado a un cliente'));
app.state.ui.brandingView='applied';app.state.ui.brandingClient='moka';
brandStory=app.renderBranding();
assert(brandStory.includes('Moka Bio'));
assert(brandStory.includes('Respuesta aplicada'));
const dog=app.appliedBrandToolAnswer(data.clients.find(x=>x.id==='moka'),data.brandingDrivers[0],data.brandingDrivers[0].tools[0]);
assert(dog.summary.includes('Moka')||dog.summary.includes('Intelligence')||dog.evidence.includes('Moka'));
const generic=app.renderBrandingMethodExplainer();
assert(generic.includes('BRANDING METHOD'));
assert(generic.includes('Qué es'));
app.state.ui.section='roadmap';
const roadmapStory=app.renderRoadmap();
assert(roadmapStory.includes('story-highlight-rail'));
assert(roadmapStory.includes('Semilla'));
assert(roadmapStory.includes('story-slide-controls'));
assert(roadmapStory.includes('story-disclosure'));
const architectPanel=app.renderArchitectPanel();
assert(architectPanel.includes('architect-utility-window'));

const menuLauncher=app.renderGlobalMenuLauncher();assert(menuLauncher.includes('global-menu-launcher'));
const menuPanel=app.renderGlobalMenuPanel();assert(menuPanel.includes('global-menu-panel'));
