'use strict';
const assert=require('assert');
const data=require('../src/data.js'); const core=require('../src/core.js');globalThis.ABRAXAS_DATA=data;globalThis.ABRAXAS_CORE=core;
require('../src/v113/domain-adapter.js'); const store=require('../src/v113/store.js'); require('../src/v113/router.js');
const c=require('../src/v113/components.js'); const shell=require('../src/v113/shell.js');
store.createStore({presentationMode:'dashboard',roleMode:'all'});
let html=shell.renderShellFrame('<main>HOME</main>');
assert(html.includes('v113-sidebar'));
assert(html.includes('Dashboard'));
assert(html.includes('Product Story'));
assert(html.includes('roleMode'));
assert(html.includes('architect-launcher-v113'));
assert(html.includes('command-launcher-v113'));
store.set({presentationMode:'story'}); html=shell.renderShellFrame('<main>STORY</main>');
assert(html.includes('is-story'));
assert(html.includes('sidebar-story-hidden'));
assert(c.renderStateView('empty',{title:'Nada pendiente'}).includes('state-empty'));
assert(c.renderStateView('loading',{title:'Procesando'}).includes('state-loading'));
assert(c.renderStateView('success',{title:'Listo'}).includes('state-success'));
assert(c.renderStateView('error',{title:'No pude mapear'}).includes('state-error'));
console.log('v1.1.3 shell/components PASS');
