(function(root,factory){const api=factory(root.V120_STORE,root.V120_DOMAIN);root.V120_ACTIONS=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(STORE,DOMAIN){
'use strict';const registry=new Map();let api=null;let hooks={render:()=>{},toast:()=>{},focus:()=>{},copyText:()=>Promise.resolve()};function configure(next){hooks={...hooks,...next};return api}function register(id,fn){registry.set(id,fn);return api||registry}function has(id){return registry.has(id)}function dispatch(id,payload={},event=null){const fn=registry.get(id);if(!fn)return false;try{fn(payload,event);return true}catch(error){console.error('ABRAXAS_ACTION_ERROR',id,error);hooks.toast({tone:'error',title:'No se pudo completar la acción',body:error.message});return false}}
function rerender(){hooks.render();}
register('nav.go',({section,origin,clientId})=>{STORE.set({section,origin:origin||STORE.get().section,selectedClientId:clientId||STORE.get().selectedClientId,commandOpen:false,modal:null,sidebarMobileOpen:false});rerender();});
register('presentation.set',({mode})=>{STORE.set({presentationMode:mode==='story'?'story':'dashboard'});rerender();});
register('brain.zoom',({value})=>{const v=Math.max(1,Math.min(2,Number(value)||1));STORE.set({brainZoom:v});globalThis.V120_BRAIN?.setZoom(v);rerender();});register('story.scroll',({target})=>{if(typeof document==='undefined')return;document.getElementById(target)?.scrollIntoView({behavior:matchMedia?.('(prefers-reduced-motion: reduce)')?.matches?'auto':'smooth',block:'start'});});
register('role.set',({role})=>{const patch={roleMode:role||'all'};if(STORE.get().presentationMode==='story'&&STORE.get().section==='dashboard')patch.presentationMode='dashboard';STORE.set(patch);rerender();});register('sidebar.toggle',()=>{const mobile=typeof innerWidth!=='undefined'&&innerWidth<=760;if(mobile)STORE.set({sidebarMobileOpen:!STORE.get().sidebarMobileOpen});else STORE.set({sidebarCollapsed:!STORE.get().sidebarCollapsed});rerender();});register('command.toggle',()=>{STORE.set({commandOpen:!STORE.get().commandOpen});rerender();});register('architect.toggle',()=>{STORE.set({architectOpen:!STORE.get().architectOpen});rerender();});
register('content.open',({id,view='overview',origin})=>{if(!DOMAIN.contentById(id))throw new Error('Content no encontrado');STORE.set({section:'studio',selectedContentId:id,studioView:view,origin:origin||STORE.get().section});rerender();});
register('studio.view',({view})=>{STORE.set({studioView:view||'overview'});rerender();});register('studio.reading',({mode})=>{STORE.set({studioReadingMode:mode||'standard'});rerender();});register('studio.back',()=>{STORE.set({section:STORE.get().origin||'library',selectedContentId:null,selectedTaskId:null});rerender();});register('production.role',({role})=>{STORE.set({roleMode:role||'all',section:'production'});rerender();});
register('task.complete',({contentId,taskId})=>{const t=DOMAIN.updateTask(contentId,taskId,{status:'done'});if(!t)throw new Error('Task no encontrada');hooks.toast({tone:'success',title:'Tarea completada',body:t.label});rerender();});
register('calendar.view',({view})=>{STORE.set({calendar:{view}});rerender();});register('calendar.month',({delta})=>{const s=STORE.get(),[y,m]=s.calendar.month.split('-').map(Number),d=new Date(y,m-1+Number(delta||0),1);STORE.set({calendar:{month:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}});rerender();});
register('calendar.move',({contentId,date,value})=>{date=date===undefined?value:date;if(date==='__NOOP__')return;if(date==='__BACKLOG__')date='';const c=DOMAIN.contentById(contentId);if(!c)throw new Error('Content no encontrado');DOMAIN.updateContent(contentId,{scheduledAt:date||null});STORE.set({calendar:{moveContentId:null}});hooks.toast({tone:'success',title:date?'Fecha actualizada':'Movido a Backlog',body:c.title});rerender();});
register('calendar.select',({date})=>{STORE.set({calendar:{selectedDate:date||null}});rerender();});register('calendar.filter',({key,value})=>{STORE.set({calendar:{filters:{[key]:value}}});rerender();});
register('architect.ask',({query})=>{STORE.set({architectQuery:query||'',architectOpen:true});rerender();});register('architect.route',({section,contentId,view,role})=>{if(role)STORE.set({roleMode:role});if(contentId)dispatch('content.open',{id:contentId,view:view||role||'overview',origin:STORE.get().section});else dispatch('nav.go',{section});});
register('factory.mode',({mode})=>{STORE.set({factory:{mode:mode||'piece',step:1}});rerender();});register('factory.step',({step})=>{STORE.set({factory:{step:Number(step)||1}});rerender();});register('factory.field',({key,value})=>{if(key==='quantity')value=Number(value)||1;STORE.set({factory:{[key]:value}});rerender();});register('factory.cadence',({key,value})=>{const f=STORE.get().factory;STORE.set({factory:{cadence:{...(f.cadence||{}),[key]:value}}});rerender();});register('factory.save',()=>{const c=globalThis.V120_FACTORY?.createContent();if(!c)throw new Error('No se pudo crear Content');hooks.toast({tone:'success',title:'Pieza guardada como AI READY',body:c.title});STORE.set({selectedContentId:c.id});rerender();});register('shim.step',({step})=>{STORE.set({shim:{step:Number(step)||1}});rerender();});register('shim.field',({key,value})=>{STORE.set({shim:{[key]:value}});rerender();});register('shim.bool',({key,checked})=>{STORE.set({shim:{[key]:checked===true||checked==='true'}});rerender();});register('shim.platform',({platform})=>{const arr=[...(STORE.get().shim.platforms||[])],i=arr.indexOf(platform);i>=0?arr.splice(i,1):arr.push(platform);STORE.set({shim:{platforms:arr}});rerender();});register('shim.structure',({structure})=>{const arr=[...(STORE.get().shim.structures||[])],i=arr.indexOf(structure);i>=0?arr.splice(i,1):arr.push(structure);STORE.set({shim:{structures:arr}});rerender();});register('shim.preset',({clientId='joc'})=>{STORE.set({shim:{clientId,step:1,verticalEnabled:true,verticalCount:'MAX',horizontalEnabled:true,horizontalCount:2,carouselEnabled:true,carouselCount:'AUTO',platforms:['Instagram','LinkedIn','YouTube'],structures:['friction','contrast','story'],context:'Podcast: preservar speakers, timestamps y texto literal; calidad primero y balance sin forzar 50/50.'}});rerender();});register('shim.copy.request',()=>{const p=globalThis.V120_SHIM?.package();if(!p)throw new Error('Paquete Shim no disponible');hooks.copyText(JSON.stringify(p.request,null,2));hooks.toast({tone:'success',title:'Request JSON copiado',body:'Listo para handoff externo.'});});
register('architect.external.copy',({query})=>{if(!globalThis.V120_ARCHITECT)throw new Error('Arquitecto no disponible');hooks.copyText(globalThis.V120_ARCHITECT.externalPrompt(query||STORE.get().architectQuery));hooks.toast({tone:'success',title:'Pregunta preparada',body:'Contexto ABRAXAS copiado para una IA externa.'});});
register('library.filter',({key,value})=>{STORE.set({library:{[key]:value}});rerender();});register('asset.select',({contentId,slotId})=>{STORE.set({assetsContentId:contentId,assetSlotId:slotId});rerender();});register('asset.path',({contentId,slotId,value})=>{DOMAIN.updateAsset(contentId,slotId,{relativePath:value,status:value?'linked':'missing'});rerender();});register('asset.status',({contentId,slotId,status})=>{const a=DOMAIN.updateAsset(contentId,slotId,{status});if(!a)throw new Error('Asset slot no encontrado');DOMAIN.addHistory(contentId,{type:'asset_status',slotId,status});hooks.toast({tone:'success',title:'Asset actualizado',body:`${slotId} · ${status}`});rerender();});register('ai.field',({key,value})=>{STORE.set({ai:{[key]:value}});rerender();});register('ai.preview',()=>{const p=globalThis.V120_AIRESULTS?.parse(STORE.get().ai.input);STORE.set({ai:{preview:p}});rerender();});register('ai.confirm',()=>{const c=globalThis.V120_AIRESULTS?.confirm(STORE.get().ai.preview);if(!c)throw new Error('No se pudo confirmar');hooks.toast({tone:'success',title:'Resultado incorporado',body:c.title});STORE.set({ai:{preview:null,input:'',destination:c.id}});rerender();});register('client.select',({clientId})=>{STORE.set({selectedClientId:clientId||null});rerender();});register('branding.mode',({mode})=>{STORE.set({brandingMode:mode});rerender();});register('branding.client',({value,clientId})=>{STORE.set({brandingClientId:value||clientId});rerender();});register('prompt.copy',({target})=>{if(typeof document==='undefined')return;const el=document.getElementById(target);if(!el)throw new Error('Prompt no encontrado');hooks.copyText(el.textContent||'');hooks.toast({tone:'success',title:'Prompt copiado',body:'Listo para ejecutar en la IA indicada.'});});
function bind(rootEl){if(!rootEl||rootEl.dataset.v120ActionsBound)return;rootEl.dataset.v120ActionsBound='1';rootEl.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const id=el.dataset.action;if(!has(id))return;const payload={...el.dataset};delete payload.action;dispatch(id,payload,e);});rootEl.addEventListener('change',e=>{const el=e.target.closest('[data-change-action]');if(!el)return;const id=el.dataset.changeAction;if(!has(id))return;const payload={...el.dataset,value:el.value,checked:el.checked};delete payload.changeAction;dispatch(id,payload,e);});rootEl.addEventListener('input',e=>{const el=e.target.closest('[data-input-action]');if(!el)return;const id=el.dataset.inputAction;if(!has(id))return;const payload={...el.dataset,value:el.value,checked:el.checked};delete payload.inputAction;dispatch(id,payload,e);});}
api={configure,register,has,dispatch,bind,list:()=>[...registry.keys()]};return api;
});
