(function(root,factory){const api=factory(root.V120_STORE,root.V120_DOMAIN,root.V120_COMPONENTS);root.V120_ARCHITECT=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(STORE,DOMAIN,C){
'use strict';
const STAGES={dashboard:'Orientación',clients:'Contexto de marca',library:'Exploración',calendar:'Planificación',factory:'Creación',production:'Producción',shim:'Extracción / automatización',airesults:'Hidratación IA',assets:'Assets',branding:'Brand Intelligence',guide:'Guía',roadmap:'Roadmap',studio:'Revisión 1×1'};
const EXPLAIN={dashboard:'Aquí decides qué requiere atención y por dónde continuar. El Dashboard prioriza siguiente acción y trabajo por responsabilidad.',factory:'He crea una pieza o un lote desde una idea, brief, campaña o necesidad y compila prompts separados de contenido y visual.',shim:'Shim parte de una grabación/transcripción con timestamps y crea un paquete para análisis externo, revisión humana y automatización confirmada.',production:'Production muestra qué falta terminar; cambia de rol para ver únicamente la responsabilidad que te corresponde.',studio:'Content Studio trabaja una sola pieza y la proyecta como guion, grabación, diseño, edición, copy, QA o publicación.',library:'Biblioteca contiene todos los Content; sirve para buscar, filtrar y abrir una pieza existente sin duplicarla.',calendar:'Calendario organiza fecha, backlog, riesgo, lotes y distribución editorial del mismo Content.',assets:'Assets vincula imágenes, video, portadas, archivos y versiones al content_id, unidad y slot correctos.',airesults:'Resultados IA devuelve resultados externos a una pieza existente mediante preview/mapping antes de confirmar.',clients:'Clientes concentra Core, formatos, Quality Packs, visual y Source Truth por marca.',branding:'Brand Intelligence permite entender el método o usarlo aplicado a una marca.',guide:'Guía explica rutas completas por objetivo y responsabilidad.',roadmap:'Roadmap muestra qué está construido, qué se valida ahora y qué sigue.'};
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function currentContent(){const s=STORE.get();return s.selectedContentId?DOMAIN.contentById(s.selectedContentId):null;}
function context(){const s=STORE.get(),content=currentContent(),pending=content?DOMAIN.openTasks(content):[],roleItems=DOMAIN.workItemsForRole(s.roleMode||'all'),priority=content?DOMAIN.nextAction(content):(roleItems[0]?.content?DOMAIN.nextAction(roleItems[0].content):null);return{section:s.section,stage:STAGES[s.section]||'ABRAXAS',roleMode:s.roleMode||'all',presentationMode:s.presentationMode||'dashboard',contentId:content?.id||null,contentTitle:content?.title||null,campaignId:content?.campaignId||null,lifecycle:content?DOMAIN.operationalStatus(content).label:null,progress:content?DOMAIN.productionProgress(content):null,pending,filters:s.section==='calendar'?s.calendar.filters:s.section==='library'?s.library:{},nextAction:priority,explanation:EXPLAIN[s.section]||'Estás dentro de ABRAXAS.'};}
function route(section,label,reason,firstAction,expectedResult,successCondition,extra={}){return{section,label,reason,firstAction,expectedResult,successCondition,...extra};}
function resolve(query=''){const q=norm(query),ctx=context();let title='Siguiente paso',summary=ctx.explanation,routes=[];
 if(/crear contenido|crear una pieza|crear algo|donde.*crear|contenido nuevo/.test(q)){title='¿Dónde puedo crear contenido?';summary='La ruta depende del insumo con el que empiezas: idea, grabación o pieza existente.';routes=[route('factory','He · Content Factory','Úsalo cuando partes de una idea, brief, campaña, pilar o tema.','Elige cliente → formato físico → formato/patrón → objetivo y contexto.','Prompt editorial + prompt visual; opcionalmente una pieza AI READY.','El prompt queda exportable o la nueva pieza aparece en Biblioteca.'),route('shim','Shim','Úsalo cuando ya tienes una grabación, podcast, entrevista o transcripción.','Pega transcript con timestamps → outputs → estructuras → review → export.','Master Prompt + request JSON; después un HTML de revisión y manifests desde la IA externa.','Los candidatos quedan revisables y solo CONFIRMADOS pasan a Automation Bridge.'),route('library','Biblioteca / Studio','Úsalo cuando el Content ya existe y quieres corregirlo, derivarlo o completar una capa.','Busca la pieza y abre la vista de Studio que corresponda.','La misma pieza actualizada, sin duplicar content_id.','La revisión queda guardada y Production refleja el siguiente pendiente.')];}
 else if(/podcast|transcripcion|entrevista|grabacion larga/.test(q)){title='Procesar una grabación o podcast';routes=[route('shim','Shim','Es la herramienta diseñada para fuente larga y timestamps.','Usa el preset del cliente si existe y pega la transcripción completa.','Candidatos, carruseles, HTML de revisión, manifest confirmado y handoff de automatización.','La selección editorial queda confirmada y exportable.')];}
 else if(/que tengo que grabar|grabar|grabacion|speaker|talento|teleprompter|guion/.test(q)){title='Preparar lo que se debe grabar';routes=[route('production','Recording Desk','Agrupa las piezas que todavía necesitan source/master video.','Cambia el rol a Grabación y abre la primera pieza no bloqueada.','Guion, recording/source, delivery y condición de terminado.','El master/source queda vinculado y la pieza deja de aparecer en Recording.',{role:'recording'}),route('production','Guion / Talento','Si solo necesitas leer/interpretar, usa la proyección de Talento.','Cambia el rol a Guion / Talento y abre el Content.','Texto hablado, cues y modo lectura/teleprompter.','La persona puede ejecutar la grabación sin información de edición.',{role:'talent'})];}
 else if(/copy|copies|caption|descripcion/.test(q)){title='Resolver copies';routes=[route('production','Copy Desk','Centraliza copies pendientes y su contexto.','Cambia el rol a Copy y abre una pieza.','Copy por plataforma + prompt + How to Use.','Los slots de copy requeridos quedan completos.',{role:'copy'})];}
 else if(/diseno|imagen|slide|portada|cover|visual/.test(q)){title='Resolver diseño';routes=[route('production','Design Desk','Agrupa slides, portadas, stills y slots visuales faltantes.','Cambia el rol a Diseño y abre la primera pieza.','Texto aprobado, función, dirección visual, referencia, prompt CON/SIN texto y asset slot.','El asset queda vinculado/aprobado en la misma pieza.',{role:'design'}),route('assets','Assets','Úsalo cuando ya tienes el archivo y necesitas vincularlo.','Busca el Content y selecciona el slot esperado.','Asset mapeado al content_id/unidad/slot correcto.','El slot deja de figurar como missing.')];}
 else if(/editar|edicion|editor|b-roll|vfx|sfx|music|musica/.test(q)){title='Resolver edición';routes=[route('production','Editing Desk','Muestra timelines que pueden editarse y sus dependencias.','Cambia el rol a Edición. Si aparece bloqueado, resuelve Recording primero.','Source + beats + B-roll + VFX + SFX + Music + referencias y prompts.','La tarea de edición queda resuelta y QA pasa a ser la siguiente etapa.',{role:'editing'})];}
 else if(/davinci|resolve/.test(q)){title='Automatización para DaVinci Resolve';routes=[route('shim','Shim → Automation Bridge','DaVinci consume la misma selección confirmada que Terminal.','Confirma candidatos en el HTML de revisión y exporta SHIM_CONFIRMED_MANIFEST.','davinciPackage + timeline/markers/subtitles/edit notes + script importable.','Resolve crea una timeline editable que respeta los rangos confirmados.')];}
 else if(/ffmpeg|terminal|command|cortes automatic/.test(q)){title='Automatización Terminal / FFmpeg';routes=[route('shim','Shim → Automation Bridge','Terminal genera derivados reproducibles sin tocar el source.','Confirma clips y exporta el manifest maestro.','CUT_AUTOMATION_PACKAGE + launcher/Python + comandos FFmpeg.','Los derivados se generan y verifican sin modificar el original.')];}
 else if(/resultado.*ia|ia.*resultado|hidratar|importar json|mapping/.test(q)){title='Devolver un resultado de IA';routes=[route('airesults','Resultados IA','Es el puente para hidratar la misma pieza sin crear copias paralelas.','Selecciona destino → tipo → pega/importa → revisa mapping → confirma.','Campos actualizados con create/update/ignore/conflict visibles.','El resultado queda en el mismo content_id y se registra el siguiente pendiente.')];}
 else if(/donde pongo.*imagen|subir.*imagen|vincular.*asset|asset/.test(q)){title='Vincular un asset';routes=[route('assets','Assets','El archivo debe quedar unido a una pieza y slot exactos.','Selecciona Content → unidad/slot → archivo → preview → confirmación.','Asset versionado y contextualizado.','El expected slot deja de estar pendiente.')];}
 else if(/bloquead|bloqueo|pendiente|que falta/.test(q)){title='Encontrar lo que está bloqueado';routes=[route('production','Production / My Work','Production ordena pendientes y dependencias por responsabilidad.','Abre My Work o el rol relevante y empieza por el primer blocker.','Lista priorizada con causa y condición de terminado.','El bloqueo desaparece y next_action avanza.')];}
 else if(/revis.*pieza|revis.*contenido|content studio|corregir.*contenido/.test(q)){title='Revisar una pieza';routes=[route('library','Biblioteca → Content Studio','La Biblioteca localiza el Content; Studio lo revisa 1×1.','Filtra/busca → abre la pieza → elige vista por responsabilidad.','Contenido editable con outline/workspace/inspector.','La revisión relevante queda completada sin perder el contexto de origen.')];}
 else if(/que hace he|he content|content factory/.test(q)){title='Qué hace He';routes=[route('factory','He · Content Factory','He transforma intención/contexto en briefs ejecutables y piezas/lotes.','Elige modo Piece o Batch y completa el wizard.','Prompts separados de contenido/visual + output schema + QA.','Puedes guardar como AI READY o ejecutar el prompt externamente.')];}
 else if(/que hace shim|que es shim/.test(q)){title='Qué hace Shim';routes=[route('shim','Shim','Shim extrae oportunidades trazables desde una fuente larga.','Fuente → Outputs → Estructuras → Review → Export.','Prompt de análisis + request JSON + contrato de HTML/manifest.','La IA externa puede devolver un review HTML sin inventar discurso.')];}
 else if(/brand intelligence|branding method|que es brand/.test(q)){title='Qué es Brand Intelligence';routes=[route('branding','Brand Intelligence','Concentra criterio, Core, formatos, fuentes, Quality Packs y método aplicado.','Elige Method Explainer o Applied to Client.','Contexto utilizable por He, QA y prompts.','La decisión de marca/formato queda clara antes de producir.')];}
 else if(/campana|campaign/.test(q)){title='Ver una campaña';routes=[route('calendar','Calendar / planificación','Muestra distribución temporal, lotes y riesgos.','Filtra por campaña.','Calendario + Planning Insight de esa campaña.','Puedes detectar y corregir desequilibrios.'),route('library','Library / contenidos de campaña','Muestra todas las piezas relacionadas sin duplicarlas.','Filtra por campaña.','Listado de Content y estados.','Puedes abrir cualquier pieza conservando el filtro.')];}
 else if(/calendar|calendariz|fecha|publico hoy|publicar hoy|que publico hoy/.test(q)){title='Planificar o publicar';routes=[route('calendar','Calendario','Organiza fechas, backlog, riesgos y mix editorial.','Abre Calendar → Today/Week/List o filtra lo que corresponda.','scheduledAt actualizado y riesgos visibles.','La pieza aparece en la fecha correcta sin duplicarse.'),route('production','Publishing Desk','Úsalo para ver qué impide publicar.','Cambia el rol a Publicación.','Bloqueos de copy/assets/QA/fecha.','La pieza puede avanzar a READY/PUBLISHED.',{role:'publishing'})];}
 else if(/como uso.*prompt|usar.*prompt|prompt/.test(q)){title='Cómo usar el prompt de esta tarea';routes=[route(ctx.section,STAGES[ctx.section]||'Módulo actual','El prompt pertenece al objeto/tarea que tienes abierto.','Copia el prompt completo → ejecútalo en la IA indicada → vuelve con el resultado al destino explicado en How to Use.','Resultado estructurado y trazable.','El resultado vuelve a la misma pieza/task, no a un objeto paralelo.')];}
 else if(/terminar.*pieza|como termino|terminada/.test(q)){title='Cómo terminar esta pieza';if(ctx.contentId&&ctx.nextAction)routes=[route(ctx.nextAction.target||'production',ctx.nextAction.label,ctx.nextAction.description||'Es el primer pendiente operativo detectado.','Resuelve este pendiente antes de pasar al siguiente.','Task/asset/gate actualizado.',ctx.nextAction.successCondition||'La pieza avanza a la siguiente etapa.',{contentId:ctx.contentId,role:ctx.nextAction.role})];else routes=[route('production','Production','Sin una pieza abierta, Production es la vista más segura para encontrar lo que falta.','Abre My Work y selecciona una pieza.','Siguiente acción concreta.','Ya existe un content_id activo y una tarea priorizada.')];}
 else if(/que hago|que sigue|primero|siguiente|ahora/.test(q)||!q){title='Siguiente paso';if(ctx.nextAction)routes=[route(ctx.nextAction.target||'production',ctx.nextAction.label,ctx.nextAction.description||'Es la siguiente acción detectada.',ctx.nextAction.description||'Abre la ruta sugerida.','Estado/tarea actualizada.',ctx.nextAction.successCondition||'El pendiente deja de estar abierto.',{contentId:ctx.nextAction.contentId,role:ctx.nextAction.role})];else routes=[route(ctx.section,STAGES[ctx.section]||'Continuar',ctx.explanation,'Usa la acción primaria de esta pantalla.','Un output claro o una siguiente acción.','La pantalla deja de mostrar un bloqueo.')];}
 else{title='Te ubico y propongo una ruta';routes=[route(ctx.section,STAGES[ctx.section]||'Continuar',ctx.explanation,ctx.nextAction?.description||'Revisa la acción primaria de esta pantalla.','Un resultado ejecutable.',ctx.nextAction?.successCondition||'La siguiente etapa queda disponible.')];}
 return{title,summary,routes,context:ctx};}
function externalPrompt(query=''){const ctx=context(),ans=resolve(query);return `ABRAXAS · ARCHITECT EXTERNAL HANDOFF · v1.2\n\nROL ACTUAL\n${ctx.roleMode}\n\nUBICACIÓN\nMódulo: ${ctx.section}\nEtapa: ${ctx.stage}\nModo: ${ctx.presentationMode}\nContent ID: ${ctx.contentId||'ninguno'}\nCampaign: ${ctx.campaignId||'no aplica'}\nLifecycle: ${ctx.lifecycle||'no aplica'}\nProgreso: ${ctx.progress??'no aplica'}\nPendientes: ${ctx.pending.map(t=>t.label).join(', ')||'ninguno'}\nFiltros: ${JSON.stringify(ctx.filters)}\n\nPREGUNTA\n${query||ans.title}\n\nPASO A PASO\nResponde con: 1) dónde entrar; 2) por qué; 3) qué seleccionar/pegar; 4) qué resultado esperar; 5) dónde llevarlo después; 6) condición exacta de terminado.\n\nNO INVENTES\nNo describas módulos, botones, automatizaciones o datos que no estén presentes en este contexto. No sugieras duplicar Content ni saltar QA/Source Truth.`;}
function render(open=STORE.get().architectOpen,query=STORE.get().architectQuery){if(!open)return'';const ctx=context(),ans=resolve(query);return `<aside class="v120-architect liquid-functional" aria-label="El Arquitecto"><header><div>${C.icon('architect')}<div><b>El Arquitecto</b><span>Guía contextual · v1.2</span></div></div><button data-action="architect.toggle" aria-label="Cerrar">×</button></header><section class="v120-architect-location"><span>${C.esc(ctx.stage)}</span><h2>${C.esc(ctx.section==='dashboard'?'Home':STAGES[ctx.section]||ctx.section)}</h2><p>${C.esc(ctx.explanation)}</p>${ctx.contentId?`<div><b>${C.esc(ctx.contentTitle)}</b><small>${C.esc(ctx.contentId)} · ${ctx.progress}% · ${C.esc(ctx.lifecycle)}</small></div>`:''}</section><div class="v120-architect-quick">${['¿Qué hago primero?','¿Dónde puedo crear contenido?','¿Qué tengo que grabar?','¿Dónde están los copies?','¿Qué tengo que editar?','¿Qué publico hoy?'].map(q=>`<button data-action="architect.ask" data-query="${C.esc(q)}">${C.esc(q)}</button>`).join('')}</div><section class="v120-architect-answer"><span>Respuesta</span><h3>${C.esc(ans.title)}</h3><p>${C.esc(ans.summary)}</p><div class="v120-architect-routes">${ans.routes.map(r=>`<article><div><b>${C.esc(r.label)}</b><p>${C.esc(r.reason)}</p></div><dl><div><dt>Primero</dt><dd>${C.esc(r.firstAction)}</dd></div><div><dt>Vas a obtener</dt><dd>${C.esc(r.expectedResult)}</dd></div><div><dt>Terminado cuando</dt><dd>${C.esc(r.successCondition)}</dd></div></dl><button class="v120-btn primary" data-action="architect.route" data-section="${C.esc(r.section)}" ${r.role?`data-role="${C.esc(r.role)}"`:''} ${r.contentId?`data-content-id="${C.esc(r.contentId)}"`:''} ${r.view?`data-view="${C.esc(r.view)}"`:''}>Ir a ${C.esc(r.label)} →</button></article>`).join('')}</div></section><div class="v120-architect-compose"><label><span>Pregunta</span><input value="${C.esc(query||'')}" data-change-action="architect.ask" data-key="query" placeholder="Ej. ¿Dónde puedo crear contenido?"></label><button class="v120-btn" data-action="architect.external.copy" data-query="${C.esc(query||ans.title)}">Preparar pregunta para IA</button></div><small class="v120-architect-privacy">Local: usa estado y conocimiento ABRAXAS. No envía datos a internet.</small></aside>`;}
return{context,resolve,externalPrompt,render,norm};
});
