(function(root,factory){const api=factory(root.V120_STORE);root.V120_BRAIN=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(STORE){
'use strict';
const BRAIN_ANATOMY=['left_hemisphere','right_hemisphere','interhemispheric_fissure','frontal_lobe','parietal_lobe','temporal_lobe','occipital_lobe','cerebellar_hint','brainstem_hint','gyri_sulci'];
const MORPH_TARGETS=['brain','routes','content_graph','production_flow','calendar','published_network'];
const PARTICLE_GLYPH='open-abraxas-chevron';let runtime=null;
function clampZoom(v){return Math.max(1,Math.min(2,Number(v)||1));}
function rng(seed=120120){let s=seed>>>0;return()=>((s=(Math.imul(s,1664525)+1013904223)>>>0)/4294967296);}
function e(x,y,cx,cy,rx,ry){const dx=(x-cx)/rx,dy=(y-cy)/ry;return dx*dx+dy*dy<=1;}
function regionAt(x,y){const side=x<0?'left':'right',ax=Math.abs(x);if(y>.62&&ax<.40)return ax<.12?'brainstem':'cerebellum';if(y>.25&&ax>.18)return 'temporal';if(y<-.28&&ax<.58)return 'frontal';if(y<.15)return 'parietal';return 'occipital';}
function anatomicalMask(x,y){const ax=Math.abs(x),side=ax>0.035;
 const crown=e(x,y,-.31,-.23,.62,.55)||e(x,y,.31,-.23,.62,.55);
 const frontal=e(x,y,-.48,-.06,.50,.55)||e(x,y,.48,-.06,.50,.55);
 const parietal=e(x,y,-.27,.12,.57,.55)||e(x,y,.27,.12,.57,.55);
 const temporal=e(x,y,-.47,.34,.43,.34)||e(x,y,.47,.34,.43,.34);
 const occipital=e(x,y,-.13,.27,.40,.43)||e(x,y,.13,.27,.40,.43);
 const cerebellum=e(x,y,-.23,.64,.28,.18)||e(x,y,.23,.64,.28,.18);
 const brainstem=e(x,y,0,.74,.115,.22);
 const fissure=ax<(.035+.026*Math.max(0,.52-y))&&y<.51;
 const lowerTrim=y>.53&&ax>.52;
 return ((crown||frontal||parietal||temporal||occipital)&&side&&!fissure&&!lowerTrim)||cerebellum||brainstem;
}
function generateBrainPoints(count,w,h,zoom=1){const r=rng(12013),pts=[],z=clampZoom(zoom),cx=w*.61,cy=h*.48,scale=Math.min(w*.58,h*.86)*z;let guard=0;while(pts.length<count&&guard<count*130){guard++;const x=r()*2-1,y=r()*1.78-.88;if(!anatomicalMask(x,y))continue;let region=regionAt(x,y);if(region==='cerebellum'&&!e(x,y,-.23,.64,.28,.18)&&!e(x,y,.23,.64,.28,.18))region=x<0?'left':'right';else if(!['cerebellum','brainstem'].includes(region))region=x<0?'left':'right';const edgeNoise=(r()-.5)*2;pts.push({x:cx+x*scale*.57+edgeNoise,y:cy+y*scale*.52+edgeNoise,region,phase:r()*6.283,size:1.2+r()*2.4,alpha:.34+r()*.62});}while(pts.length<count)pts.push({x:cx,y:cy,region:'brainstem',phase:0,size:1.4,alpha:.5});return pts;}
function targetPoints(name,count,w,h,zoom=1){if(name==='brain')return generateBrainPoints(count,w,h,zoom);const r=rng(220+name.length),pts=[],cx=w*.55,cy=h*.5,ww=Math.min(w*.68,1100),hh=Math.min(h*.70,720);for(let i=0;i<count;i++){let x,y;if(name==='routes'){const lane=i%7,row=Math.floor(i/7)%14;x=cx-ww*.43+lane*(ww*.86/6)+(r()-.5)*9;y=cy-hh*.42+row*(hh*.84/13)+(r()-.5)*7;}else if(name==='content_graph'){const a=i/count*Math.PI*2*7,rr=(.05+.43*i/count)*Math.min(w,h);x=cx+Math.cos(a)*rr;y=cy+Math.sin(a)*rr*.62;}else if(name==='production_flow'){const col=i%6,row=Math.floor(i/6)%10;x=cx-ww*.42+col*(ww*.84/5)+(r()-.5)*12;y=cy-hh*.40+row*(hh*.80/9)+(r()-.5)*8;}else if(name==='calendar'){const col=i%7,row=Math.floor(i/7)%6;x=cx-ww*.40+col*(ww*.80/6)+(r()-.5)*5;y=cy-hh*.33+row*(hh*.66/5)+(r()-.5)*5;}else{const a=r()*Math.PI*2,rr=Math.sqrt(r())*Math.min(w,h)*.42;x=cx+Math.cos(a)*rr;y=cy+Math.sin(a)*rr*.68;}pts.push({x,y,region:name,phase:r()*6.283,size:1+r()*2.0,alpha:.32+r()*.60});}return pts;}
function drawChevron(ctx,p,t){const pulse=.88+.12*Math.sin(t*.001+p.phase),s=p.size*pulse;ctx.globalAlpha=p.alpha;ctx.strokeStyle=p.region==='brainstem'?'#b78338':p.region==='cerebellum'?'#d0a65e':p.alpha>.72?'#f4ead6':p.alpha>.52?'#d8b46c':'#8a6532';ctx.lineWidth=Math.max(.65,s*.34);ctx.beginPath();ctx.moveTo(p.x-s,p.y+s*.58);ctx.lineTo(p.x,p.y-s*.74);ctx.lineTo(p.x+s,p.y+s*.58);ctx.stroke();}
function brainTransform(w,h,z){const scale=Math.min(w*.58,h*.86)*clampZoom(z);return{cx:w*.61,cy:h*.48,sx:scale*.57,sy:scale*.52};}
function drawBrainStructure(ctx,w,h,z){const {cx,cy,sx,sy}=brainTransform(w,h,z);ctx.save();ctx.lineWidth=1.15;ctx.strokeStyle='rgba(244,234,214,.22)';ctx.shadowBlur=18;ctx.shadowColor='rgba(216,180,108,.08)';
 // recognizable bilateral contour with lobed lower temporal/cerebellar mass
 ctx.beginPath();ctx.moveTo(cx,cy-sy*.86);ctx.bezierCurveTo(cx-sx*.18,cy-sy*.98,cx-sx*.72,cy-sy*.90,cx-sx*.86,cy-sy*.52);ctx.bezierCurveTo(cx-sx*1.03,cy-sy*.18,cx-sx*.92,cy+sy*.12,cx-sx*.72,cy+sy*.28);ctx.bezierCurveTo(cx-sx*.78,cy+sy*.55,cx-sx*.53,cy+sy*.66,cx-sx*.34,cy+sy*.57);ctx.bezierCurveTo(cx-sx*.26,cy+sy*.76,cx-sx*.12,cy+sy*.78,cx,cy+sy*.63);ctx.bezierCurveTo(cx+sx*.12,cy+sy*.78,cx+sx*.26,cy+sy*.76,cx+sx*.34,cy+sy*.57);ctx.bezierCurveTo(cx+sx*.53,cy+sy*.66,cx+sx*.78,cy+sy*.55,cx+sx*.72,cy+sy*.28);ctx.bezierCurveTo(cx+sx*.92,cy+sy*.12,cx+sx*1.03,cy-sy*.18,cx+sx*.86,cy-sy*.52);ctx.bezierCurveTo(cx+sx*.72,cy-sy*.90,cx+sx*.18,cy-sy*.98,cx,cy-sy*.86);ctx.stroke();
 ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.24)';ctx.beginPath();ctx.moveTo(cx,cy-sy*.85);ctx.bezierCurveTo(cx-sx*.035,cy-sy*.44,cx+sx*.025,cy+sy*.12,cx,cy+sy*.48);ctx.stroke();
 // cerebellar lobulation + brainstem hint
 ctx.strokeStyle='rgba(216,180,108,.20)';for(const side of [-1,1]){ctx.beginPath();ctx.ellipse?.(cx+side*sx*.24,cy+sy*.63,sx*.22,sy*.12,side*.08,0,Math.PI*2);ctx.stroke();}ctx.beginPath();ctx.moveTo(cx-sx*.07,cy+sy*.58);ctx.lineTo(cx-sx*.055,cy+sy*.92);ctx.lineTo(cx+sx*.055,cy+sy*.92);ctx.lineTo(cx+sx*.07,cy+sy*.58);ctx.stroke();
 // gyri/sulci: dense but restrained curves by hemisphere
 ctx.strokeStyle='rgba(244,234,214,.10)';ctx.lineWidth=.85;const rows=[-.65,-.48,-.31,-.14,.03,.20,.37];for(const side of [-1,1])for(let j=0;j<rows.length;j++){const y=rows[j],phase=(j%2?-.08:.08)*side;ctx.beginPath();ctx.moveTo(cx+side*sx*.10,cy+sy*y);ctx.bezierCurveTo(cx+side*sx*.30,cy+sy*(y-.12+phase),cx+side*sx*.56,cy+sy*(y+.12-phase),cx+side*sx*.73,cy+sy*(y+.01));ctx.bezierCurveTo(cx+side*sx*.63,cy+sy*(y+.17),cx+side*sx*.38,cy+sy*(y+.19),cx+side*sx*.18,cy+sy*(y+.12));ctx.stroke();}
 // internal cluster network
 ctx.strokeStyle='rgba(216,180,108,.085)';const nodes=[[-.54,-.42],[-.30,-.62],[-.17,-.22],[-.47,.04],[-.28,.32],[-.12,.48],[.54,-.42],[.30,-.62],[.17,-.22],[.47,.04],[.28,.32],[.12,.48],[0,.05]];ctx.beginPath();for(let i=0;i<nodes.length;i++){for(let j=i+1;j<nodes.length;j++){const a=nodes[i],b=nodes[j];if(Math.hypot(a[0]-b[0],a[1]-b[1])<.44){ctx.moveTo(cx+a[0]*sx,cy+a[1]*sy);ctx.lineTo(cx+b[0]*sx,cy+b[1]*sy);}}}ctx.stroke();ctx.restore();}
function morph(name){if(!runtime||!MORPH_TARGETS.includes(name))return;runtime.target=name;runtime.targets=targetPoints(name,runtime.particles.length,runtime.w,runtime.h,runtime.zoom);}
function setZoom(v){const z=clampZoom(v);STORE?.set({brainZoom:z});if(runtime){runtime.zoom=z;runtime.targets=targetPoints(runtime.target,runtime.particles.length,runtime.w,runtime.h,z);}return z;}
function init(canvasId='v120BrainCanvas'){if(typeof document==='undefined')return null;const canvas=document.getElementById(canvasId);if(!canvas)return null;if(runtime?.raf)cancelAnimationFrame(runtime.raf);const ctx=canvas.getContext('2d');if(!ctx)return null;const rect=canvas.getBoundingClientRect(),w=Math.max(900,rect.width||innerWidth||1200),h=Math.max(620,rect.height||innerHeight||760),dpr=Math.min(2,devicePixelRatio||1);canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);const reduced=matchMedia?.('(prefers-reduced-motion: reduce)')?.matches||false,count=w<950?1050:1850,zoom=clampZoom(STORE?.get?.().brainZoom||1),r=rng(12044),particles=Array.from({length:count},()=>({x:w*(.38+r()*.45),y:h*(.16+r()*.66),region:'left',phase:r()*6.283,size:1+r()*2,alpha:.32+r()*.62}));runtime={canvas,ctx,w,h,particles,targets:targetPoints('brain',count,w,h,zoom),target:'brain',zoom,reduced,raf:null};function frame(t=0){ctx.clearRect(0,0,w,h);if(runtime.target==='brain')drawBrainStructure(ctx,w,h,runtime.zoom);for(let i=0;i<particles.length;i++){const p=particles[i],q=runtime.targets[i],ease=reduced?1:.06;p.x+=(q.x-p.x)*ease;p.y+=(q.y-p.y)*ease;p.region=q.region||p.region;if(!reduced&&runtime.target==='brain'){p.x+=Math.sin(t*.00038+p.phase)*.018;p.y+=Math.cos(t*.00032+p.phase)*.014;}drawChevron(ctx,p,t);}ctx.globalAlpha=1;if(!reduced)runtime.raf=requestAnimationFrame(frame);}frame(performance?.now?.()||0);return runtime;}
function destroy(){if(runtime?.raf&&typeof cancelAnimationFrame!=='undefined')cancelAnimationFrame(runtime.raf);runtime=null;}
function observeStory(){if(typeof document==='undefined'||typeof IntersectionObserver==='undefined')return null;const obs=new IntersectionObserver(entries=>{const active=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(active){const t=active.target.dataset.brainTarget;if(t)morph(t);}}, {threshold:[.35,.55,.75]});document.querySelectorAll('[data-brain-target]').forEach(el=>obs.observe(el));return obs;}
return{BRAIN_ANATOMY,MORPH_TARGETS,PARTICLE_GLYPH,clampZoom,anatomicalMask,generateBrainPoints,targetPoints,drawBrainStructure,init,destroy,morph,setZoom,observeStory,get runtime(){return runtime;}};
});
