(function(root,factory){const api=factory(root.V120_STORE,root.V120_DOMAIN,root.V120_COMPONENTS);root.V120_CALENDAR=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(STORE,DOMAIN,C){
'use strict';
function monthDays(month){const [y,m]=month.split('-').map(Number),first=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),offset=(first.getDay()+6)%7,out=[];for(let i=0;i<offset;i++)out.push(null);for(let d=1;d<=days;d++)out.push(`${month}-${String(d).padStart(2,'0')}`);return out;}
function dateRange(month,view){const [y,m]=month.split('-').map(Number);if(view==='week'){const start=new Date(y,m-1,10),end=new Date(start);end.setDate(start.getDate()+6);return[start.toISOString().slice(0,10),end.toISOString().slice(0,10)];}return[`${month}-01`,`${month}-${String(new Date(y,m,0).getDate()).padStart(2,'0')}`];}
function risk(c){const issues=[];const next=DOMAIN.nextAction(c);if(DOMAIN.missingAssets(c).length)issues.push(`${DOMAIN.missingAssets(c).length} assets`);if(DOMAIN.openTasks(c).length)issues.push(`${DOMAIN.openTasks(c).length} tasks`);if(next.role==='recording')issues.push('recording');return issues;}
function filters(){const s=STORE.get().calendar.filters,clients=[['all','Todos los clientes'],...DOMAIN.allClients().map(c=>[c.id,c.name])],campaigns=[['all','Todas las campañas'],...DOMAIN.campaigns().map(c=>[c.id,c.name])];return `<div class="v120-calendar-filters">${C.select('Cliente','calendar.filter','client',s.client,clients)}${C.select('Campaña','calendar.filter','campaign',s.campaign,campaigns)}${C.select('Lote','calendar.filter','lot',s.lot,[['all','Todos'],['L1','L1'],['L2','L2'],['L3','L3']])}${C.select('Estado','calendar.filter','status',s.status,[['all','Todos'],['NEEDS_SOURCE','Needs source'],['COPY','Copy'],['DESIGN','Design'],['EDITING','Editing'],['QA','QA'],['PRODUCTION','Production'],['SCHEDULED_AT_RISK','Scheduled at risk'],['READY_TO_PUBLISH','Ready'],['SCHEDULED','Scheduled'],['PUBLISHED','Published']])}</div>`;}
function moveSelect(c){const month=STORE.get().calendar.month,[y,m]=month.split('-').map(Number),days=new Date(y,m,0).getDate(),opts=Array.from({length:days},(_,i)=>`${month}-${String(i+1).padStart(2,'0')}`);return `<select class="v120-move-select" aria-label="Mover ${C.esc(c.title)}" data-change-action="calendar.move" data-content-id="${C.esc(c.id)}"><option value="__NOOP__">Mover…</option>${opts.map(d=>`<option value="${d}">${d}</option>`).join('')}<option value="__BACKLOG__">Backlog</option></select>`;}
function card(c){const issues=risk(c),client=DOMAIN.clientById(c.clientId),campaign=DOMAIN.campaignById(c.campaignId);return `<article class="v120-calendar-card ${issues.length?'risk':''}" draggable="true" data-content-id="${C.esc(c.id)}"><button data-action="content.open" data-id="${C.esc(c.id)}" data-view="overview" data-origin="calendar"><span>${C.esc(client?.name||c.clientId)} · ${C.esc(c.lot||'—')}</span><b>${C.esc(c.title)}</b><small>${C.esc(c.physicalType)} · ${C.esc(DOMAIN.operationalStatus(c).label)}</small>${campaign?`<em>${C.esc(campaign.name)}</em>`:''}${issues.length?`<i>${C.icon('warning')}${C.esc(issues.join(' · '))}</i>`:''}</button>${moveSelect(c)}</article>`;}
function monthView(rows,month){const days=monthDays(month);return `<div class="v120-calendar-month"><div class="v120-weekdays">${['Lun','Mar','Mié','Jue','Vie','Sáb','Dom'].map(x=>`<span>${x}</span>`).join('')}</div><div class="v120-month-grid">${days.map(date=>date?`<section class="v120-day" data-date="${date}"><header><b>${Number(date.slice(-2))}</b><span>${rows.filter(c=>c.scheduledAt===date).length}</span></header>${rows.filter(c=>c.scheduledAt===date).map(card).join('')}</section>`:'<section class="v120-day empty"></section>').join('')}</div></div>`;}
function weekView(rows,start,end){const days=[];for(let d=new Date(start+'T12:00:00');d<=new Date(end+'T12:00:00');d.setDate(d.getDate()+1))days.push(d.toISOString().slice(0,10));return `<div class="v120-week-board">${days.map(date=>`<section><header><span>${new Date(date+'T12:00:00').toLocaleDateString('es',{weekday:'short'})}</span><b>${date.slice(-2)}</b></header>${rows.filter(c=>c.scheduledAt===date).map(card).join('')||'<p>Sin contenido</p>'}</section>`).join('')}</div>`;}
function listView(rows){return `<div class="v120-calendar-list">${rows.sort((a,b)=>(a.scheduledAt||'').localeCompare(b.scheduledAt||'')).map(c=>`<div><time>${C.esc(c.scheduledAt||'Backlog')}</time>${card(c)}</div>`).join('')}</div>`;}
function backlogView(){const rows=DOMAIN.allContents().filter(c=>!c.scheduledAt);return `<div class="v120-backlog-grid">${rows.length?rows.map(card).join(''):C.stateView('success','Backlog limpio','Todo el contenido tiene una fecha o está publicado.')}</div>`;}
function insight(rows){const ins=DOMAIN.planningInsight(rows);return `<aside class="v120-planning-insight v120-panel"><span>Planning Insight</span><h2>Qué está pasando en esta ventana.</h2><div class="v120-insight-groups"><section><b>Formatos</b>${Object.entries(ins.byType).map(([k,v])=>`<p>${C.esc(k)}<strong>${v}</strong></p>`).join('')}</section><section><b>Lotes</b>${Object.entries(ins.byLot).map(([k,v])=>`<p>${C.esc(k)}<strong>${v}</strong></p>`).join('')}</section></div>${ins.warnings.length?`<div class="v120-insight-warnings">${ins.warnings.map(w=>`<p>${C.icon('warning')}${C.esc(w)}</p>`).join('')}</div>`:`<div class="v120-insight-ok">${C.icon('check')}<p>No detecto desequilibrios básicos con las reglas actuales.</p></div>`}</aside>`;}
function render(){const s=STORE.get(),cal=s.calendar,view=cal.view||'month',[start,end]=dateRange(cal.month,view),rows=DOMAIN.planningWindow(start,end,cal.filters);const body=view==='week'?weekView(rows,start,end):view==='list'?listView(rows):view==='backlog'?backlogView():monthView(rows,cal.month);return `<section class="v120-calendar">${C.sectionTitle('PLANIFICACIÓN','Calendario editorial','Fecha, campaña, lotes, readiness y riesgo en una sola superficie.',C.actionButton('←','calendar.month',{delta:-1})+`<span class="v120-month-label">${cal.month}</span>`+C.actionButton('→','calendar.month',{delta:1}))}<div class="v120-calendar-toolbar"><div class="v120-segmented">${[['month','Month'],['week','Week'],['list','List'],['backlog','Backlog']].map(([id,label])=>`<button class="${view===id?'active':''}" data-action="calendar.view" data-view="${id}">${label}</button>`).join('')}</div>${filters()}</div><div class="v120-calendar-layout"><main class="v120-panel">${body}</main>${insight(rows)}</div></section>`;}
return{render,monthDays,dateRange,risk};
});
