(function(root,factory){const api=factory(root.ABRAXAS_DATA||(typeof require!=='undefined'?require('../data.js'):null),root.ABRAXAS_CORE||(typeof require!=='undefined'?require('../core.js'):null));root.V120_DOMAIN=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(DATA,CORE){
'use strict';const source=DATA||{clients:[],contents:[],campaigns:[],savedViews:[],brandingDrivers:[],roadmap:[]};let runtime=JSON.parse(JSON.stringify(source));
const DONE=new Set(['done','approved']);const VIDEO_TYPES=new Set(['reel','horizontal']);
function allContents(){return runtime.contents||[]}function allClients(){return runtime.clients||[]}function campaigns(){return runtime.campaigns||[]}function contentById(id){return allContents().find(c=>c.id===id)||null}function clientById(id){return allClients().find(c=>c.id===id)||null}function campaignById(id){return campaigns().find(c=>c.id===id)||null}
function openTasks(c){return(c?.productionTasks||[]).filter(t=>!DONE.has(t.status))}function asset(c,slot){return(c?.expectedAssets||[]).find(a=>a.slotId===slot)||null}function assetStatus(c,slot){return asset(c,slot)?.status||'missing'}function missingAssets(c,kind){return(c?.expectedAssets||[]).filter(a=>(!kind||a.kind===kind)&&!['approved','ready','done','linked'].includes(a.status))}
function productionProgress(c){const tasks=c?.productionTasks||[];if(!tasks.length)return c?.lifecycle==='PUBLISHED'?100:0;return Math.round(tasks.filter(t=>DONE.has(t.status)).length/tasks.length*100)}
function operationalStatus(c){
 if(!c)return{id:'UNKNOWN',label:'Sin estado',tone:'neutral',reason:'Content no disponible.'};
 if(c.lifecycle==='ARCHIVED')return{id:'ARCHIVED',label:'Archivado',tone:'neutral',reason:'La pieza está archivada.'};
 if(c.lifecycle==='PUBLISHED')return{id:'PUBLISHED',label:'Publicado',tone:'success',reason:'La publicación está registrada como cerrada.'};
 const tasks=openTasks(c),missing=missingAssets(c),video=VIDEO_TYPES.has(c.physicalType),masterMissing=video&&assetStatus(c,'master-video')==='missing';
 const has=(...types)=>tasks.some(t=>types.includes(t.type));
 if(c.scheduledAt&&(tasks.length||missing.length))return{id:'SCHEDULED_AT_RISK',label:'Calendarizado · en riesgo',tone:'warning',reason:`Tiene fecha, pero conserva ${tasks.length} tareas y ${missing.length} assets pendientes.`};
 if(masterMissing)return{id:'NEEDS_SOURCE',label:'Necesita source / grabación',tone:'warning',reason:'Falta el source/master video necesario para continuar la edición.'};
 if(has('copy'))return{id:'COPY',label:'Copy pendiente',tone:'info',reason:'Faltan copies requeridos por plataforma.'};
 if(has('visual','cover')||missing.some(a=>a.kind==='image'))return{id:'DESIGN',label:'Diseño pendiente',tone:'info',reason:'Faltan visuales, portadas o assets gráficos.'};
 if(video&&has('video'))return{id:'EDITING',label:'Edición pendiente',tone:'info',reason:'El source está disponible y la pieza necesita montaje/edición.'};
 if(has('qa'))return{id:'QA',label:'QA pendiente',tone:'warning',reason:'Falta completar QA antes de publicar.'};
 if(has('publish'))return{id:'PUBLISHING',label:'Publicación pendiente',tone:'info',reason:'La pieza está en el cierre de publicación.'};
 if(tasks.length||missing.length)return{id:'PRODUCTION',label:'En producción',tone:'info',reason:`Quedan ${tasks.length} tareas y ${missing.length} assets.`};
 if(c.scheduledAt)return{id:'SCHEDULED',label:'Calendarizado',tone:'success',reason:`Listo y calendarizado para ${c.scheduledAt}.`};
 return{id:'READY_TO_PUBLISH',label:'Listo para publicar',tone:'success',reason:'No se detectan tareas ni assets pendientes.'};
}
function baseItem(c,role,kind){return{id:`${kind}:${c.id}`,kind,role,contentId:c.id,content:c,client:clientById(c.clientId),campaign:campaignById(c.campaignId),progress:productionProgress(c),scheduledAt:c.scheduledAt||null,blocked:false,blockedReason:'',priority:c.scheduledAt?1:2};}
function workItemForContent(c,role){if(!c)return null;const item=baseItem(c,role,role);const tasks=openTasks(c),video=VIDEO_TYPES.has(c.physicalType),masterMissing=video&&assetStatus(c,'master-video')==='missing';
 if(role==='strategy'){if(['PUBLISHED','ARCHIVED'].includes(c.lifecycle))return null;item.label='Estrategia / Editorial';item.tasks=tasks.filter(t=>['editorial','structure','source'].includes(t.type));item.next='Revisar tesis, formato, fuente y estructura';return item;}
 if(role==='talent'){if(!video||['PUBLISHED','ARCHIVED'].includes(c.lifecycle))return null;item.label='Guion / Talento';item.kind='talent';item.tasks=[];item.next='Leer/ensayar el guion y sus cues';return item;}
 if(role==='copy'){const copy=tasks.filter(t=>t.type==='copy');const hasCopies=c.copies&&Object.values(c.copies).some(Boolean);if(!copy.length&&hasCopies)return null;item.tasks=copy;item.label='Copy';item.next=copy[0]?.label||'Completar copies por plataforma';return item;}
 if(role==='recording'){if(!video||['PUBLISHED','ARCHIVED'].includes(c.lifecycle))return null;if(!masterMissing&&['RECORDED','PRODUCTION','READY','READY_TO_PUBLISH','SCHEDULED'].includes(c.lifecycle))return null;item.kind='recording';item.label='Grabación / Source';item.tasks=tasks.filter(t=>t.type==='video');item.next=masterMissing?'Grabar o vincular source/master video':'Revisar toma';return item;}
 if(role==='design'){const design=tasks.filter(t=>['visual','cover'].includes(t.type));const imgs=missingAssets(c,'image');if(!design.length&&!imgs.length)return null;item.kind='design';item.label='Diseño';item.tasks=design;item.missingAssets=imgs;item.next=imgs[0]?`Resolver ${imgs[0].slotId}`:design[0]?.label||'Revisar visual';return item;}
 if(role==='editing'){if(!video||['PUBLISHED','ARCHIVED'].includes(c.lifecycle))return null;item.kind='editing';item.label='Edición';item.tasks=tasks.filter(t=>t.type==='video');item.blocked=masterMissing;item.blockedReason=masterMissing?'Recording/source todavía no está disponible. Completa Grabación o vincula el master antes de editar.':'';item.next=item.blocked?'Resolver Recording/source':'Montar beats, B-roll, VFX, SFX y música';return item;}
 if(role==='qa'){const qa=tasks.filter(t=>t.type==='qa');if(!qa.length&&['PUBLISHED','ARCHIVED'].includes(c.lifecycle))return null;item.kind='qa';item.label='QA';item.tasks=qa;item.next=qa[0]?.label||'Ejecutar gates editorial/visual/source';return item;}
 if(role==='publishing'){if(['PUBLISHED','ARCHIVED'].includes(c.lifecycle))return null;const pub=tasks.filter(t=>t.type==='publish');item.kind='publishing';item.label='Publicación';item.tasks=pub;const other=tasks.filter(t=>t.type!=='publish'),assets=missingAssets(c);item.blocked=other.length>0||assets.length>0;item.blockedReason=item.blocked?`${other.length} tareas y ${assets.length} assets siguen abiertos.`:'';item.next=item.blocked?'Resolver bloqueos antes de publicar':c.scheduledAt?'Publicar/confirmar salida':'Calendarizar';return item;}
 return item;
}
function workItemsForRole(role='all'){if(role==='all')return allContents().filter(c=>!['ARCHIVED'].includes(c.lifecycle)).map(c=>{const x=baseItem(c,'all','content');x.label='Content';x.next=nextAction(c).label;return x;});return allContents().map(c=>workItemForContent(c,role)).filter(Boolean)}
function tasksForRole(role='all'){if(role==='all')return allContents().flatMap(c=>openTasks(c).map(task=>({contentId:c.id,content:c,task})));return workItemsForRole(role).flatMap(w=>(w.tasks||[]).map(task=>({contentId:w.contentId,content:w.content,task,workItem:w})))}
function nextAction(c){const op=operationalStatus(c);if(op.id==='PUBLISHED')return{label:'Publicado',role:'publishing',target:'library',contentId:c.id,description:'El ciclo está cerrado.',successCondition:'La publicación permanece registrada.'};if(op.id==='ARCHIVED')return{label:'Archivado',role:'all',target:'library',contentId:c.id,description:'La pieza está archivada.',successCondition:'Sin acción pendiente.'};for(const role of ['recording','design','copy','editing','qa','publishing']){const w=workItemForContent(c,role);if(w&&(!w.blocked||role!=='editing'))return{label:w.next,role,target:role==='publishing'?'calendar':'production',contentId:c.id,description:w.blockedReason||w.next,successCondition:`${w.label} deja de estar pendiente`};}return{label:'Revisar pieza',role:'all',target:'studio',contentId:c.id,description:'No hay un bloqueo operativo detectado.',successCondition:'Pieza revisada'};}

function addContent(content){if(!content?.id)throw new Error('content_id requerido');if(contentById(content.id))throw new Error('content_id duplicado');runtime.contents.push(JSON.parse(JSON.stringify(content)));return contentById(content.id);}
function addHistory(contentId,entry){const c=contentById(contentId);if(!c)return null;c.history=Array.isArray(c.history)?c.history:[];c.history.push({at:new Date().toISOString(),...entry});return c.history.at(-1);}
function updateAsset(contentId,slotId,patch={}){const c=contentById(contentId);if(!c)return null;c.expectedAssets=Array.isArray(c.expectedAssets)?c.expectedAssets:[];let a=c.expectedAssets.find(x=>x.slotId===slotId);if(!a){a={slotId,kind:patch.kind||'image',status:'missing'};c.expectedAssets.push(a);}Object.assign(a,patch);return a;}
function updateContent(id,patch){const c=contentById(id);if(!c)return null;Object.assign(c,patch);return c}function updateTask(contentId,taskId,patch){const t=contentById(contentId)?.productionTasks?.find(x=>x.id===taskId);if(!t)return null;Object.assign(t,patch);return t}function reset(){runtime=JSON.parse(JSON.stringify(source));return runtime}
function planningWindow(start,end,filter={}){return allContents().filter(c=>c.scheduledAt&&c.scheduledAt>=start&&c.scheduledAt<=end).filter(c=>(filter.client==='all'||!filter.client||c.clientId===filter.client)&&(filter.lot==='all'||!filter.lot||c.lot===filter.lot)&&(filter.status==='all'||!filter.status||operationalStatus(c).id===filter.status)&&(filter.campaign==='all'||!filter.campaign||c.campaignId===filter.campaign));}
function planningInsight(rows){const byType={},byPillar={},byLot={};for(const c of rows){byType[c.physicalType]=(byType[c.physicalType]||0)+1;byPillar[c.pillar||'Sin pilar']=(byPillar[c.pillar||'Sin pilar']||0)+1;byLot[c.lot||'Sin lote']=(byLot[c.lot||'Sin lote']||0)+1;}const warnings=[];if((byType.reel||0)>=4&&(byType.carousel||0)===0)warnings.push('Alta concentración de Reels y ningún carrusel en la ventana.');const topP=Object.entries(byPillar).sort((a,b)=>b[1]-a[1])[0];if(topP&&rows.length>=4&&topP[1]/rows.length>.6)warnings.push(`${topP[0]} concentra más del 60% de la ventana.`);if(rows.length&&!(byLot.L1||0))warnings.push('La ventana no contiene piezas L1 principales.');return{byType,byPillar,byLot,warnings};}
return{version:'1.2',source,get data(){return runtime},allContents,allClients,campaigns,contentById,clientById,campaignById,openTasks,asset,assetStatus,missingAssets,productionProgress,operationalStatus,workItemForContent,workItemsForRole,tasksForRole,nextAction,addContent,addHistory,updateAsset,updateContent,updateTask,planningWindow,planningInsight,reset};
});
