(function(root,factory){const api=factory(root.V120_STORE,root.V120_DOMAIN,root.V120_COMPONENTS);root.V120_STORY=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(STORE,DOMAIN,C){
'use strict';
const HOTSPOTS=[['factory','He',45,28,'Crea desde una idea, brief o campaña.'],['shim','Shim',71,25,'Convierte una grabación en oportunidades trazables.'],['production','Production',78,50,'Coordina qué falta y quién debe hacerlo.'],['assets','Assets',64,71,'Vincula archivos al Content y al slot exacto.'],['calendar','Calendar',47,72,'Ordena cuándo sale y qué está en riesgo.'],['branding','Brand',43,51,'Protege Core, formatos, fuentes y criterio.']];
function hotspotLayer(){return `<div class="v120-brain-hotspots">${HOTSPOTS.map(([id,label,x,y,desc])=>`<button class="v120-brain-hotspot" style="--x:${x}%;--y:${y}%" data-action="nav.go" data-section="${id}"><span></span><i></i><b>${label}</b><aside><strong>${label}</strong><p>${desc}</p><em>Abrir herramienta →</em></aside></button>`).join('')}</div>`;}
function zoom(){const z=STORE.get().brainZoom||1;return `<div class="v120-brain-zoom liquid-functional"><button data-action="brain.zoom" data-value="${Math.max(1,z-.1).toFixed(2)}">−</button><span>${Math.round(z*100)}%</span><input type="range" min="1" max="2" step=".05" value="${z}" data-change-action="brain.zoom"><button data-action="brain.zoom" data-value="${Math.min(2,z+.1).toFixed(2)}">＋</button><small>100% mínimo · 200% máximo</small></div>`;}
function home(){const first=DOMAIN.allContents()[0];return `<article class="v120-product-story"><section class="v120-story-hero" data-brain-target="brain"><canvas id="v120BrainCanvas" aria-hidden="true"></canvas><div class="v120-story-scrim"></div><div class="v120-story-copy liquid-functional"><span>ABRAXAS · CREATIVE OPERATIONS</span><h1>Tu operación editorial.<br><em>En un solo sistema.</em></h1><p>Un mismo Content atraviesa criterio, IA, personas, producción, assets, aprobación y publicación sin perder su identidad.</p><div><button class="v120-btn primary" data-action="story.scroll" data-target="v120Highlights">Explorar el sistema</button><button class="v120-btn" data-action="presentation.set" data-mode="dashboard">Abrir Dashboard</button></div></div><div class="v120-brain-stage">${hotspotLayer()}${zoom()}</div></section>
<section id="v120Highlights" class="v120-story-block" data-brain-target="routes"><header><span>Get the highlights</span><h2>Una ruta para cada tipo de trabajo.</h2><p>Empieza por el resultado que necesitas; ABRAXAS mantiene el mismo objeto debajo.</p></header><div class="v120-highlight-rail">${[['factory','Create','Idea → estructura → prompt'],['shim','Shim','Transcript → revisión → automation'],['production','Produce','Roles → tareas → dependencias'],['studio','Review','Una pieza → múltiples vistas'],['calendar','Publish','Fecha → riesgo → publicado']].map(([id,t,d])=>`<button ${id==='studio'&&first?`data-action="content.open" data-id="${C.esc(first.id)}" data-view="overview" data-origin="story"`:`data-action="nav.go" data-section="${id}"`}><i>${C.icon(id==='studio'?'studio':id)}</i><h3>${t}</h3><p>${d}</p><em>Explorar →</em></button>`).join('')}</div></section>
<section class="v120-story-block v120-closer" data-brain-target="content_graph"><header><span>Take a closer look</span><h2>Un Content. Muchas capas.</h2><p>La pieza no se duplica cuando cambia de manos. Cambia la proyección.</p></header><div class="v120-content-orbit"><div class="center">CONTENT</div>${['Strategy','Script','Copy','Visual','Assets','QA','Calendar'].map((x,i)=>`<div class="o${i+1}">${x}</div>`).join('')}</div></section>
<section class="v120-story-showcase" data-brain-target="production_flow"><div class="v120-story-sticky"><span>How it works</span><h2>La complejidad vive debajo.<br>La siguiente acción queda arriba.</h2><p>Una pieza mantiene relaciones, pero cada persona solo ve la tarea que debe resolver.</p></div><div class="v120-story-steps">${[['01','Definir','Brand + Format + Campaign'],['02','Crear','He o Shim'],['03','Producir','Roles + Tasks + Assets'],['04','Revisar','Content Studio + QA'],['05','Publicar','Calendar + History']].map(([n,t,d])=>`<article><b>${n}</b><h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>
<section class="v120-story-block" data-brain-target="calendar"><header><span>Built for how you work</span><h2>Una persona puede hacerlo todo.<br>Un equipo puede ver solo lo suyo.</h2></header><div class="v120-role-story">${[['talent','Guion / Talento','Texto hablado, delivery y teleprompter.'],['copy','Copy','Copies, contexto y prompt por plataforma.'],['recording','Grabación','Qué grabar, cómo y condición de terminado.'],['design','Diseño','Texto aprobado, visual, referencia y asset.'],['editing','Edición','Timeline y capas audiovisuales completas.'],['qa','QA','Gates, claims, sources y blockers.']].map(([r,t,d])=>`<button data-action="role.set" data-role="${r}"><b>${t}</b><p>${d}</p><em>Ver como ${t} →</em></button>`).join('')}</div></section>
<section class="v120-story-block v120-transcript-story" data-brain-target="published_network"><header><span>From transcript to timeline</span><h2>Shim automatiza decisiones confirmadas.</h2><p>Transcripción → Review HTML → CONFIRMADO → manifest único → Terminal/FFmpeg y DaVinci Resolve.</p></header><div class="v120-transcript-flow"><span>Transcript</span><i>→</i><span>Review HTML</span><i>→</i><span>Confirmed Manifest</span><i>↙</i><span>Terminal</span><span>DaVinci</span></div><button class="v120-btn primary" data-action="nav.go" data-section="shim">Abrir Shim</button></section>
<section class="v120-story-finale"><span>One Content. Every Team.</span><h2>ABRAXAS coordina criterio, personas e IA sin duplicar la pieza.</h2><button class="v120-btn primary" data-action="presentation.set" data-mode="dashboard">Volver al Dashboard</button></section></article>`;}
function clients(){return `<article class="v120-product-story simple"><section class="v120-story-simple-hero"><span>Client Intelligence</span><h1>Cada marca conserva su criterio.</h1><p>La infraestructura se comparte. Core, formatos, voz, visual y Source Truth no.</p></section><div class="v120-story-client-grid">${DOMAIN.allClients().map(c=>`<button data-action="nav.go" data-section="clients" data-client-id="${C.esc(c.id)}"><b>${C.esc(c.name)}</b><p>${C.esc(c.brandCore?.core||c.category||'')}</p><em>Abrir Intelligence →</em></button>`).join('')}</div></article>`;}
function branding(){return `<article class="v120-product-story simple"><section class="v120-story-simple-hero"><span>Brand Intelligence</span><h1>El criterio antes que el contenido.</h1><p>Core, método, formatos, Quality Pack y fuentes forman el contexto que protege cada salida.</p></section></article>`;}
function roadmap(){return `<article class="v120-product-story simple"><section class="v120-story-simple-hero"><span>Roadmap</span><h1>Primero operación estable.<br>Después ecosistema.</h1></section><div class="v120-roadmap-story">${(DOMAIN.data.roadmap||[]).map((r,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><h3>${C.esc(r.name||r.id)}</h3><p>${C.esc(r.subtitle||r.detail||'')}</p></article>`).join('')}</div></article>`;}
function render(section){return section==='clients'?clients():section==='branding'?branding():section==='roadmap'?roadmap():home();}
return{HOTSPOTS,render,home,clients,branding,roadmap,hotspotLayer,zoom};
});
