(function(root,factory){const api=factory();root.V120_STORE=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const KEY='ABRAXAS_A_v1.2_UI';
const DEFAULT={version:'1.2',section:'dashboard',presentationMode:'dashboard',roleMode:'all',sidebarCollapsed:false,sidebarMobileOpen:false,commandOpen:false,architectOpen:false,architectQuery:'',architectAnswer:null,selectedContentId:null,selectedTaskId:null,studioView:'overview',studioReadingMode:'standard',origin:'dashboard',calendar:{view:'month',month:'2026-08',selectedDate:null,filters:{client:'all',campaign:'all',lot:'all',status:'all'},moveContentId:null},library:{query:'',client:'all',status:'all',format:'all',savedView:'all'},factory:{mode:'piece',step:1},shim:{step:1,clientId:'joc'},ai:{destination:null,type:'package',input:'',preview:null},brainZoom:1,storyChapter:'hero',toast:null,modal:null};
let state=JSON.parse(JSON.stringify(DEFAULT));const listeners=new Set();
function clone(v){return JSON.parse(JSON.stringify(v));}
function migrate(input){const old=input?.ui||input||{};return {...clone(DEFAULT),...old,version:'1.2',presentationMode:old.presentationMode||old.viewMode||'dashboard',roleMode:old.roleMode==='script'?'talent':old.roleMode||'all',calendar:{...clone(DEFAULT.calendar),...(old.calendar||{}),month:old.calendar?.month||old.calendarMonth||'2026-08',filters:{...DEFAULT.calendar.filters,...(old.calendar?.filters||{})}},library:{...clone(DEFAULT.library),...(old.library||{})},factory:{...clone(DEFAULT.factory),...(old.factory||{})},shim:{...clone(DEFAULT.shim),...(old.shim||{})},ai:{...clone(DEFAULT.ai),...(old.ai||{})},brainZoom:Math.max(1,Math.min(2,Number(old.brainZoom)||1))};}
function notify(prev){for(const fn of listeners){try{fn(state,prev);}catch(e){console.warn('ABRAXAS store listener failed',e);}}}
function set(patch){const prev=state;const next={...state,...patch};if(patch.calendar)next.calendar={...state.calendar,...patch.calendar,filters:{...state.calendar.filters,...(patch.calendar.filters||{})}};if(patch.library)next.library={...state.library,...patch.library};if(patch.factory)next.factory={...state.factory,...patch.factory};if(patch.shim)next.shim={...state.shim,...patch.shim};if(patch.ai)next.ai={...state.ai,...patch.ai};state=next;save();notify(prev);return state;}
function get(){return state;}function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);}function reset(){const prev=state;state=clone(DEFAULT);save();notify(prev);return state;}
function save(){if(typeof localStorage!=='undefined')try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}return state;}
function load(){if(typeof localStorage==='undefined')return state;try{const own=localStorage.getItem(KEY);if(own){state=migrate(JSON.parse(own));return state;}for(const k of ['ABRAXAS_A_v1.1.3_UI','ABRAXAS_A_v1.1.2_STATE','ABRAXAS_A_v1.0_STATE']){const raw=localStorage.getItem(k);if(raw){state=migrate(JSON.parse(raw));save();return state;}}}catch(e){console.warn('ABRAXAS v1.2 state recovery',e);}return state;}
return{KEY,DEFAULT,get,set,load,save,reset,subscribe,migrate};
});
