(function(root,factory){const api=factory();root.V120_TECHNIQUES=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';let cleanups=[];function onCleanup(fn){cleanups.push(fn);return fn;}function reduced(){return typeof matchMedia!=='undefined'&&matchMedia('(prefers-reduced-motion: reduce)').matches;}
function initReveals(){if(typeof document==='undefined')return null;const els=[...document.querySelectorAll('.v120-story-block,.v120-story-showcase,.v120-story-finale,.v120-panel')];if(reduced()||typeof IntersectionObserver==='undefined'){els.forEach(e=>e.classList.add('is-visible'));return null;}els.forEach(e=>e.classList.add('v120-reveal'));const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.12});els.forEach(e=>obs.observe(e));return onCleanup(()=>obs.disconnect());}
function initCalendarDrag(){if(typeof document==='undefined')return null;let dragId=null;const start=e=>{const card=e.target.closest?.('.v120-calendar-card[draggable="true"]');if(!card)return;dragId=card.dataset.contentId;e.dataTransfer?.setData('text/plain',dragId);card.classList.add('is-dragging');};const end=e=>{e.target.closest?.('.v120-calendar-card')?.classList.remove('is-dragging');dragId=null;};const over=e=>{if(e.target.closest?.('.v120-day'))e.preventDefault();};const drop=e=>{const day=e.target.closest?.('.v120-day[data-date]');if(!day)return;e.preventDefault();const id=dragId||e.dataTransfer?.getData('text/plain');if(id)globalThis.V120_ACTIONS?.dispatch('calendar.move',{contentId:id,date:day.dataset.date},e);};document.addEventListener('dragstart',start);document.addEventListener('dragend',end);document.addEventListener('dragover',over);document.addEventListener('drop',drop);return onCleanup(()=>{document.removeEventListener('dragstart',start);document.removeEventListener('dragend',end);document.removeEventListener('dragover',over);document.removeEventListener('drop',drop);});}
function initCommandSearch(){if(typeof document==='undefined')return null;const input=document.querySelector('#v120CommandSearch');if(!input)return null;const handler=()=>{const q=input.value.toLowerCase();document.querySelectorAll('.v120-command>div button').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q));};input.addEventListener('input',handler);return onCleanup(()=>input.removeEventListener('input',handler));}
function initMagneticCTA(){if(typeof document==='undefined'||reduced()||matchMedia?.('(pointer: coarse)').matches)return null;const els=[...document.querySelectorAll('.v120-story-hero .v120-btn.primary')],moves=[];for(const el of els){const move=e=>{const r=el.getBoundingClientRect(),x=(e.clientX-(r.left+r.width/2))/r.width*6,y=(e.clientY-(r.top+r.height/2))/r.height*6;el.style.transform=`translate(${x}px,${y}px)`;};const leave=()=>el.style.removeProperty('transform');el.addEventListener('pointermove',move);el.addEventListener('pointerleave',leave);moves.push(()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerleave',leave);});}return onCleanup(()=>moves.forEach(f=>f()));}
function initBrain(){if(globalThis.V120_STORE?.get().presentationMode==='story'&&globalThis.V120_STORE?.get().section==='dashboard'){globalThis.V120_BRAIN?.init();const obs=globalThis.V120_BRAIN?.observeStory();if(obs)onCleanup(()=>obs.disconnect());}}
function init(){destroy();initReveals();initCalendarDrag();initCommandSearch();initMagneticCTA();initBrain();return true;}function destroy(){for(const fn of cleanups.splice(0))try{fn()}catch(e){}globalThis.V120_BRAIN?.destroy?.();}
return{init,destroy,initReveals,initCalendarDrag,initCommandSearch,initMagneticCTA};
});
