export const NARRATIVE_STATES = [
  {
    id: 'S0',
    name: 'HERO',
    plateAssetId: 'SOURCE_01',
    plateWebp: 'assets/plates/plate_01_hero.webp',
    platePng: 'assets/plates/plate_01_hero.png',
    chapterEn: '0. PREMISE // GENESIS',
    chapterEs: '0. PREMISA // GÉNESIS',
    titleEn: 'Criterion becomes infrastructure.',
    titleEs: 'El criterio se convierte en infraestructura.',
    leadEn: 'ABRAXAS is an operating architecture for transforming intent into structured, observable, producible and measurable reality.',
    leadEs: 'ABRAXAS es una arquitectura operativa para transformar la intención en realidad estructurada, observable, producible y medible.',
    focusedNode: 'HERO'
  },
  {
    id: 'S1',
    name: 'FOUR_WORLDS',
    plateAssetId: 'SOURCE_10',
    plateWebp: 'assets/plates/plate_10_master_monument.webp',
    platePng: 'assets/plates/plate_10_master_monument.png',
    chapterEn: '1. ARCHITECTURE // FOUR WORLDS',
    chapterEs: '1. ARQUITECTURA // CUATRO MUNDOS',
    titleEn: 'One system. Many degrees of manifestation.',
    titleEs: 'Un sistema. Múltiples grados de manifestación.',
    leadEn: 'The Giza monument structures reality across Atziluth, Beri\'ah, Yetzirah, and Assiah, anchoring intent to empirical manifestation.',
    leadEs: 'El monumento piramidal estructura la realidad a través de Atziluth, Beri\'ah, Yetzirah y Assiah, anclando la intención a la manifestación empírica.',
    focusedNode: 'CORE'
  },
  {
    id: 'S2',
    name: 'YOD',
    plateAssetId: 'SOURCE_06',
    plateWebp: 'assets/plates/plate_06_arquitecto_lens.webp',
    platePng: 'assets/plates/plate_06_arquitecto_lens.png',
    chapterEn: '2. INTELLIGENCE // SUPERNAL TRIAD',
    chapterEs: '2. INTELIGENCIA // TRÍADA SUPERNAL',
    titleEn: 'Before something exists, it must become possible.',
    titleEs: 'Antes de que algo exista, debe volverse posible.',
    leadEn: 'In the Golden Emanation Chamber, YOD evaluates brand voice criteria, hook taxonomies, and opportunity gaps without blank-slate guesswork.',
    leadEs: 'En la Cámara de Emanación Dorada, YOD evalúa criterios de voz de marca, taxonomías de hooks y brechas de oportunidad sin conjeturas.',
    focusedNode: 'YOD'
  },
  {
    id: 'S3',
    name: 'CONTENIDO',
    plateAssetId: 'SOURCE_03',
    plateWebp: 'assets/plates/plate_03_continuity_axis.webp',
    platePng: 'assets/plates/plate_03_continuity_axis.png',
    chapterEn: '3. IDENTITY // CONTINUITY AXIS',
    chapterEs: '3. IDENTIDAD // EJE DE CONTINUIDAD',
    titleEn: 'The form changes. The identity survives.',
    titleEs: 'La forma cambia. La identidad sobrevive.',
    leadEn: 'Contenido preserves single-piece identity across all revisions through a content-addressed DAG and the vertical sapphire Continuity Axis.',
    leadEs: 'Contenido preserva la identidad única a través de todas las revisiones mediante un DAG direccionable por contenido y el Eje de Continuidad de zafiro.',
    focusedNode: 'CONTENIDO'
  },
  {
    id: 'S4',
    name: 'SHIM',
    plateAssetId: 'SOURCE_04',
    plateWebp: 'assets/plates/plate_04_shim_metrology.webp',
    platePng: 'assets/plates/plate_04_shim_metrology.png',
    chapterEn: '4. REALITY // DA\'AT METROLOGY',
    chapterEs: '4. REALIDAD // METROLOGÍA DE DA\'AT',
    titleEn: 'Planned is not observed. Observed is not resolved.',
    titleEs: 'Lo planificado no es lo observado. Lo observado no es lo resuelto.',
    leadEn: 'SHIM scans the discrepancy between scripted intent and recorded media, preventing silent drift before downstream production begins.',
    leadEs: 'SHIM escanea la discrepancia entre la intención guionada y el metraje grabado, previniendo desviaciones antes de la producción.',
    focusedNode: 'SHIM'
  },
  {
    id: 'S5',
    name: 'VAV',
    plateAssetId: 'SOURCE_05',
    plateWebp: 'assets/plates/plate_05_vav_cathedral.webp',
    platePng: 'assets/plates/plate_05_vav_cathedral.png',
    chapterEn: '5. FORMATION // YETZIRAH CATHEDRAL',
    chapterEs: '5. FORMACIÓN // CATEDRAL YETZIRAH',
    titleEn: 'Information becomes media.',
    titleEs: 'La información se convierte en medios.',
    leadEn: 'Deep in the bedrock forge, VAV operates three industrial tracks: non-destructive cuts, kinetic typography hierarchies, and spring-physics motions.',
    leadEs: 'En la forja interior, VAV opera tres pistas industriales: cortes no destructivos, tipografía cinética y físicas de movimiento.',
    focusedNode: 'VAV'
  },
  {
    id: 'S6',
    name: 'HE',
    plateAssetId: 'SOURCE_02',
    plateWebp: 'assets/plates/plate_02_he_macro.webp',
    platePng: 'assets/plates/plate_02_he_macro.png',
    chapterEn: '6. OPERATION // ASSIAH VISIBILITY',
    chapterEs: '6. OPERACIÓN // VISIBILIDAD EN ASSIAH',
    titleEn: 'Complexity becomes operable.',
    titleEs: 'La complejidad se vuelve operable.',
    leadEn: 'HE governs tasks, deadlines, recording sessions, and reviews through human-accessible operational portals.',
    leadEs: 'HE gobierna tareas, plazos, sesiones de grabación y revisiones a través de portales operativos accesibles para humanos.',
    focusedNode: 'HE'
  },
  {
    id: 'S7',
    name: 'PUBLISHING',
    plateAssetId: 'SOURCE_07',
    plateWebp: 'assets/plates/plate_07_moon_loop.webp',
    platePng: 'assets/plates/plate_07_moon_loop.png',
    chapterEn: '7. EXTERNAL LOOP // THE CELESTIAL MOON',
    chapterEs: '7. BUCLE EXTERNO // LA LUNA CÓSMICA',
    titleEn: 'Manifestation leaves the Pyramid. Evidence returns.',
    titleEs: 'La manifestación sale de la Pirámide. La evidencia retorna.',
    leadEn: 'Publisher dispatches frozen versions to external channels, while telemetry feedback loops return audience signals into YOD.',
    leadEs: 'Publisher despacha versiones congeladas a canales externos, mientras los bucles de retorno telemétrico alimentan a YOD.',
    focusedNode: 'PUBLISHING'
  },
  {
    id: 'S8',
    name: 'ADAPTATION',
    plateAssetId: 'SOURCE_08',
    plateWebp: 'assets/plates/plate_08_contenido_portal.webp',
    platePng: 'assets/plates/plate_08_contenido_portal.png',
    chapterEn: '8. ADAPTATION // DIMENSION A',
    chapterEs: '8. ADAPTACIÓN // DIMENSIÓN A',
    titleEn: 'The system returns, but never to the same state.',
    titleEs: 'El sistema retorna, pero nunca al mismo estado.',
    leadEn: 'Adaptive dimension A preserves cognitive stratigraphy—memory, learning, and criteria refinement—closing the perpetual intelligence loop.',
    leadEs: 'La dimensión adaptativa A preserva la estratigrafía cognitiva (memoria, aprendizaje y refinamiento de criterio), cerrando el bucle.',
    focusedNode: 'CORE'
  },
  {
    id: 'S9',
    name: 'OPERATIONAL_CORE',
    plateAssetId: 'SOURCE_09',
    plateWebp: 'assets/plates/plate_09_system_dashboard.webp',
    platePng: 'assets/plates/plate_09_system_dashboard.png',
    chapterEn: '9. OPERATIONAL CORE // COMMAND',
    chapterEs: '9. NÚCLEO OPERATIVO // MANDO',
    titleEn: 'Enter the operating system.',
    titleEs: 'Entra al sistema operativo.',
    leadEn: 'Transition from cinematic manifesto to live operational dashboard, examine empirical evidence ledgers, and explore all 13 module operators.',
    leadEs: 'Transita del manifiesto cinematográfico al panel de control operativo, examina el registro de evidencias y explora los 13 operadores.',
    focusedNode: 'CORE'
  }
];
