(function(root,factory){const api=factory(root.V120_STORE,root.V120_COMPONENTS);root.V120_SHELL=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(typeof globalThis!=='undefined'?globalThis:this,function(STORE,C){
'use strict';
const NAV=[['dashboard','Home','dashboard'],['clients','Clientes','clients'],['library','Biblioteca','library'],['calendar','Calendario','calendar'],['factory','He · Content Factory','factory'],['production','Producción','production'],['shim','Shim','shim'],['airesults','Resultados IA','airesults'],['assets','Assets','assets'],['branding','Brand Intelligence','branding'],['guide','Guía','guide'],['roadmap','Roadmap','roadmap']];
const ROLES=[['all','Yo hago todo'],['strategy','Estrategia'],['talent','Guion / Talento'],['copy','Copy'],['recording','Grabación'],['design','Diseño'],['editing','Edición'],['qa','QA'],['publishing','Publicación']];
function storyActive(s){return s.presentationMode==='story'&&['dashboard','clients','branding','roadmap'].includes(s.section)}
function nav(){const s=STORE.get(),story=storyActive(s);return `<aside class="v120-sidebar liquid-functional ${s.sidebarCollapsed?'collapsed':''} ${story?'story-hidden':''} ${s.sidebarMobileOpen?'mobile-open':''}"><div class="v120-brand">${C.brandIcon()}<div><b>ABRAXAS</b><span>Creative Operations System</span></div>${C.actionButton('', 'sidebar.toggle',{}, {icon:'menu'})}</div><nav>${NAV.map(([id,label,ic])=>`<button class="v120-nav ${s.section===id?'active':''}" data-action="nav.go" data-section="${id}">${C.icon(ic)}<span>${label}</span></button>`).join('')}</nav><footer><b>v1.2</b><span>Product Recovery</span></footer></aside>`;}
function topbar(){const s=STORE.get(),label=NAV.find(x=>x[0]===s.section)?.[1]||'ABRAXAS';return `<header class="v120-topbar liquid-functional"><div class="v120-top-leading">${C.actionButton('', 'sidebar.toggle',{}, {icon:'menu'})}<div><b>${label}</b><span>${ROLES.find(x=>x[0]===s.roleMode)?.[1]||s.roleMode}</span></div></div><div class="v120-top-actions"><div class="v120-segmented" aria-label="Representación"><button class="${s.presentationMode==='dashboard'?'active':''}" data-action="presentation.set" data-mode="dashboard">Dashboard</button><button class="${s.presentationMode==='story'?'active':''}" data-action="presentation.set" data-mode="story">Product Story</button></div>${C.select('Rol','role.set','role',s.roleMode,ROLES,'compact')}<button class="v120-icon-button" data-action="command.toggle" aria-label="Command Palette">⌘K</button></div></header>`;}
function command(){const s=STORE.get();if(!s.commandOpen)return'';return `<div class="v120-command-backdrop"><section class="v120-command liquid-functional"><header>${C.icon('search')}<input id="v120CommandSearch" placeholder="Buscar herramienta o acción…"><button data-action="command.toggle">Esc</button></header><div>${NAV.map(([id,label,ic])=>`<button data-action="nav.go" data-section="${id}">${C.icon(ic)}<span>${label}</span><small>Abrir</small></button>`).join('')}</div></section></div>`;}
function renderShell(content){const s=STORE.get(),story=storyActive(s);return `<div class="v120-app ${story?'is-story':'is-dashboard'} ${s.sidebarCollapsed?'sidebar-collapsed':''}">${nav()}<div class="v120-main">${topbar()}<main class="v120-workspace">${content}</main></div>${command()}<button class="v120-architect-launcher liquid-functional" data-action="architect.toggle">${C.icon('architect')}<span>El Arquitecto</span></button><div id="v120ArchitectMount"></div><div id="v120ToastMount"></div></div>`;}
return{NAV,ROLES,storyActive,renderShell,nav,topbar,command};
});
