#!/bin/bash
set -euo pipefail

TARGET="${ABRAXAS_PACKAGE_ROOT:-$HOME/Downloads/ABRAXAS_V4_2_24_APPLE40M_RESUME_MASTER_PACKAGE}"
chmod +x "$TARGET/TERMINAL/ABRAXAS_MONITOR_APPLE40M.command"
open "$TARGET/TERMINAL/ABRAXAS_MONITOR_APPLE40M.command"

